// What horse behaviour patterns mean — from open-access veterinary sources.
//
// Every pattern cites the sources it rests on (ids in SOURCES). Where no source
// gives a number, the entry says so: thresholds EquiCare uses in those places
// are our operational choice, marked `ours: true`, and belong in front of a vet.
// `equicare` says honestly what the system can observe today:
//   measured     — read by the camera now
//   prototype    — a camera heuristic exists but is not validated on horses
//   label        — no detector yet; staff mark it on footage to teach one
//   sensor       — needs other hardware (IMU, flow meter)
//   not_visible  — a stall camera at 3–4 m cannot see it
// Compiled 2026-09-27 from ~55 open-access sources; extended 2026-10-04 from a
// six-part review (rest, pain, vices and welfare, feeding and heat, monitoring
// studies, communication and the Indian context) — about 120 sources more.
// Paywalled originals are cited through their abstracts (access: "abstract")
// or the open papers that describe them.

export const SOURCES = {
  merck_colic:       { title: "Merck Vet Manual — Overview of Colic in Horses (Moore, 2026)", url: "https://www.merckvetmanual.com/digestive-system/colic-in-horses/overview-of-colic-in-horses", kind: "vet manual" },
  maskato2020:       { title: "Maskato et al. 2020, Animals — Equine Acute Abdominal Pain Scale (EAAPS) revalidation", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC7760242/", kind: "peer-reviewed" },
  vandierendonck2020:{ title: "van Dierendonck et al. 2020 — EQUUS-COMPASS / FAP items (donkey version)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC7070438/", kind: "peer-reviewed" },
  auer2021:          { title: "Auer et al. 2021, Animals — Activity time budgets as a welfare tool", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8002676/", kind: "peer-reviewed" },
  torcivia2021:      { title: "Torcivia & McDonnell 2021 — Equine Discomfort Ethogram", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC7931104/", kind: "peer-reviewed" },
  dallacosta2014:    { title: "Dalla Costa et al. 2014, PLOS ONE — Horse Grimace Scale", url: "https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0092281", kind: "peer-reviewed" },
  gleerup2015:       { title: "Gleerup et al. 2015 — An equine pain face", url: "https://pubmed.ncbi.nlm.nih.gov/25082060", kind: "peer-reviewed", access: "abstract" },
  ask2020:           { title: "Ask et al. 2020, Animals — Pain behaviour in the box", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC7699379/", kind: "peer-reviewed" },
  broome2019:        { title: "Broomé et al. 2019, CVPR — Pain recognition from video over time", url: "https://arxiv.org/abs/1901.02106", kind: "peer-reviewed" },
  merck_laminitis:   { title: "Merck Vet Manual — Laminitis in Horses", url: "https://www.merckvetmanual.com/musculoskeletal-system/disorders-of-the-foot-in-horses/laminitis-in-horses", kind: "vet manual" },
  rutgers_tpr:       { title: "Rutgers NJAES FS1262 — Temperature, pulse and respiration", url: "https://njaes.rutgers.edu/fs1262/", kind: "extension" },
  merck_resp:        { title: "Merck Vet Manual — Respiratory Diseases of Horses", url: "https://www.merckvetmanual.com/respiratory-system/respiratory-diseases-of-horses/overview-of-respiratory-diseases-of-horses", kind: "vet manual" },
  lampang2023:       { title: "Na Lampang et al. 2023, Vet World — Infrared vs rectal temperature in horses", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10844792", kind: "peer-reviewed" },
  transport_eye2024: { title: "2024 — Eye temperature, rectal temperature and cortisol after transport", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11240744/", kind: "peer-reviewed" },
  alberghina2025:    { title: "Alberghina et al. 2025, Frontiers — Non-contact thermometry reference intervals", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12043634/", kind: "peer-reviewed" },
  merck_parturition: { title: "Merck Vet Manual — Parturition in Horses", url: "https://www.merckvetmanual.com/management-and-nutrition/management-of-reproduction-horses/parturition-in-horses", kind: "vet manual" },
  csu_foaling:       { title: "Colorado State Univ. ERL — Prediction of foaling and normal foaling", url: "https://vetmedbiosci.colostate.edu/erl/2022/12/01/prediction-of-foaling-and-normal-foaling/", kind: "extension" },
  merck_perinatal:   { title: "Merck Vet Manual — Perinatal Mare and Foal Care", url: "https://www.merckvetmanual.com/management-and-nutrition/preventative-health-care-and-husbandry-of-horses/perinatal-mare-and-foal-care", kind: "vet manual" },
  hausberger2009:    { title: "Hausberger et al. 2009, PLoS ONE — Abnormal repetitive behaviours in working horses", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC2763287/", kind: "peer-reviewed" },
  merck_behaviour:   { title: "Merck Vet Manual — Behavior Problems of Horses (Houpt, 2025)", url: "https://www.merckvetmanual.com/behavior/behavior-of-horses/behavior-problems-of-horses", kind: "vet manual" },
  ufifas_vm257:      { title: "UF/IFAS VM257 — Stereotypic behaviours in horses", url: "https://ask.ifas.ufl.edu/publication/VM257", kind: "extension" },
  brauns2025:        { title: "Brauns et al. 2025, Animals — Repetitive behaviour episode rule", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12523708/", kind: "peer-reviewed" },
  mata2024:          { title: "Mata, Boyton & Young 2024, Animals — Behaviour before feeding", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11672559/", kind: "peer-reviewed" },
  mazzola2016:       { title: "Mazzola et al. 2016, Vet Med Int — Stereotypies and feeding", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5081461/", kind: "peer-reviewed" },
  mejia2022:         { title: "Mejía et al. 2022, Vet World — Stereotypies in Colombian Creole horses", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC9178590/", kind: "peer-reviewed" },
  cortisol2024:      { title: "PLoS ONE 2024 — Competition and stereotypic behaviour in Thoroughbreds (cortisol)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11458048/", kind: "peer-reviewed" },
  nowak2024:         { title: "Nowak et al. 2024, Front Pain Res — Weight shifting and pain", url: "https://www.frontiersin.org/journals/pain-research/articles/10.3389/fpain.2024.1410302/full", kind: "peer-reviewed" },
  rutgers_manure:    { title: "Westendorf & Krogmann 2006, Rutgers — Horse manure management", url: "https://esc.rutgers.edu/fact_sheet/horse-manure-management-bedding-use/", kind: "extension" },
  lpelc:             { title: "LPELC — Stall waste production and management", url: "https://lpelc.org/stall-waste-production-and-management/", kind: "extension" },
  outouil2026:       { title: "Outouil et al. 2026, JAALAS — Stall size and behaviour", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC13446403/", kind: "peer-reviewed" },
  williams2015:      { title: "Williams et al. 2015, Equine Vet J — Pasture to stable: faecal output and gut motility", url: "https://pubmed.ncbi.nlm.nih.gov/24528106/", kind: "peer-reviewed" },
  merck_urolith:     { title: "Merck Vet Manual — Urolithiasis in Horses (Divers, 2025)", url: "https://www.merckvetmanual.com/urinary-system/noninfectious-diseases-of-the-urinary-system-in-large-animals/urolithiasis-in-horses", kind: "vet manual" },
  griffin2019:       { title: "Griffin 2019, Univ. Kentucky / eXtension — Horse feeding behaviour", url: "https://horses.extension.org/horse-feeding-behavior/", kind: "extension" },
  giannone2026:      { title: "Giannone et al. 2026, Vet Quarterly — Deep-learning stall video study", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC13126938/", kind: "peer-reviewed" },
  ogilvie1994:       { title: "Ogilvie-Graham 1994 — Time budget studies in stalled horses (Edinburgh thesis)", url: "https://era.ed.ac.uk/handle/1842/29924", kind: "thesis", access: "abstract" },
  kjellberg2021:     { title: "Kjellberg et al. 2021, Animals — Lying behaviour in open barns", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8614411/", kind: "peer-reviewed" },
  kelemen2021:       { title: "Kelemen et al. 2021, Animals — Lying time, bouts and REM deprivation", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8614510/", kind: "peer-reviewed" },
  gobbo2025:         { title: "Gobbo et al. 2025 — Lying in riding-school horses", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12104677", kind: "peer-reviewed" },
  murase2018:        { title: "Murase et al. 2018, J Equine Sci — Foal lying behaviour", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC6145866/", kind: "peer-reviewed" },
  zimmer2026:        { title: "Zimmer et al. 2026, Frontiers Vet Sci — Sleep architecture and lying behaviour (EEG)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC13491436/", kind: "peer-reviewed" },
  burla2017:         { title: "Burla et al. 2017, Frontiers Vet Sci — Bedding and lying", url: "https://www.frontiersin.org/journals/veterinary-science/articles/10.3389/fvets.2017.00023/full", kind: "peer-reviewed" },
  merck_emergency:   { title: "Merck Vet Manual — Emergency care for horses", url: "https://www.merckvetmanual.com/special-pet-topics/emergencies/emergency-care-for-horses", kind: "vet manual" },
  ext_tpr:           { title: "eXtension — Temperature, pulse and respiration in a horse", url: "https://horses.extension.org/temperature-pulse-and-respiration-in-a-horse/", kind: "extension" },
  psu_colic:         { title: "Penn State Extension — Colic: signs and management", url: "https://extension.psu.edu/colic-what-are-the-signs-and-how-to-manage", kind: "extension" },
  psu_healthy:       { title: "Penn State Extension — Recognizing a healthy horse", url: "https://extension.psu.edu/recognizing-a-healthy-horse", kind: "extension" },
  merck_temp_table:  { title: "Merck Vet Manual — Normal rectal temperature ranges", url: "https://www.merckvetmanual.com/multimedia/table/normal-rectal-temperature-ranges", kind: "vet manual" },
  merck_resp_table:  { title: "Merck Vet Manual — Resting respiratory rates", url: "https://www.merckvetmanual.com/multimedia/table/resting-respiratory-rates", kind: "vet manual" },
  adriaens2022:      { title: "Adriaens et al. 2022, Wageningen — Lying down / getting up from video box features (dairy cows)", url: "https://edepot.wur.nl/584493", kind: "peer-reviewed" },
  deeposit2025:      { title: "DeePosit 2025 — Thermal detection of urine and faeces deposits (mice)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12393880/", kind: "peer-reviewed" },
  yang2025:          { title: "Yang et al. 2025, Ecol Evol — Stereotypy detection by tracking + periodicity (slow lorises)", url: "https://doi.org/10.1002/ece3.72304", kind: "peer-reviewed", access: "abstract" },
  merck_heaves:      { title: "Merck Vet Manual — Recurrent airway obstruction (heaves)", url: "https://www.merckvetmanual.com/horse-owners/lung-and-airway-disorders-of-horses/recurrent-airway-obstruction-heaves-in-horses", kind: "vet manual" },

  // ---- added 2026-10-04 (deep research: six reviews, ~300 sources read) ---- //
  // colic, pain, lameness
  curtis2015:        { title: "Curtis et al. 2015, Acta Vet Scand — Primary evaluation of 1,016 horses with colic", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4596518", kind: "peer-reviewed" },
  bowden2019:        { title: "Bowden et al. 2019, Equine Vet J — Owners recognising colic (REACT)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC7027804/", kind: "peer-reviewed" },
  react:             { title: "Univ. Nottingham / BHS — REACT colic campaign", url: "https://nottingham.ac.uk/cevm/practice-based-research/working-with-practices/colic-project.aspx", kind: "extension" },
  eerdekens2024:     { title: "Eerdekens et al. 2024, Equine Vet J — Early detection of induced colic with leg accelerometers", url: "https://doi.org/10.1111/evj.14069", kind: "peer-reviewed", access: "abstract" },
  torcivia2020:      { title: "Torcivia & McDonnell 2020, Animals — Caretaker visits hide discomfort behaviour", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC7070845", kind: "peer-reviewed" },
  csu_comfort:       { title: "Colorado State Univ. — Equine Comfort Assessment Scale (Blossom et al. 2007)", url: "https://vetmedbiosci.colostate.edu/vth/equine-pain-scale", kind: "extension" },
  uellendahl2024:    { title: "Uellendahl et al. 2024, Sensors — Resting hind legs and lying in hind-lame horses", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11598077/", kind: "peer-reviewed" },
  wylie_laminitis:   { title: "Wylie et al. — Laminitis in Great Britain 2009–2011: clinical signs in 577 cases", url: "https://rvc-repository.worktribe.com/output/1413050/a-cohort-study-of-equine-laminitis-in-great-britain-2009-2011-estimation-of-disease-frequency-and-description-of-clinical-signs-in-577-cases", kind: "peer-reviewed", access: "abstract" },
  lundblad2021:      { title: "Lundblad et al. 2021, PLoS ONE — Facial expressions of stress (transport, isolation)", url: "https://doi.org/10.1371/journal.pone.0241532", kind: "peer-reviewed" },
  merck_exertional:  { title: "Merck Vet Manual — Exertional myopathies (tying-up)", url: "https://www.merckvetmanual.com/musculoskeletal-system/myopathies-in-horses/exertional-myopathies-in-horses", kind: "vet manual" },
  // illness and infection
  merck_strangles:   { title: "Merck Vet Manual — Strangles in horses", url: "https://www.merckvetmanual.com/veterinary/respiratory-system/respiratory-diseases-of-horses/strangles-in-horses", kind: "vet manual" },
  msd_influenza:     { title: "MSD Vet Manual — Equine influenza", url: "https://www.msdvetmanual.com/veterinary/respiratory-system/respiratory-diseases-of-horses/equine-influenza", kind: "vet manual" },
  msd_pleuro:        { title: "MSD Vet Manual — Pleuropneumonia in horses", url: "https://www.msdvetmanual.com/veterinary/respiratory-system/respiratory-diseases-of-horses/pleuropneumonia-in-horses", kind: "vet manual" },
  duz2010:           { title: "Duz et al. 2010, Res Vet Sci — Counting coughs in horses (audio vs video)", url: "https://eprints.gla.ac.uk/36078", kind: "peer-reviewed" },
  virmani2010:       { title: "Virmani et al. 2010, Vet Microbiol — Equine influenza outbreak in India 2008–09", url: "https://doi.org/10.1016/j.vetmic.2009.12.007", kind: "peer-reviewed", access: "abstract" },
  singha2020:        { title: "Singha et al. 2020, Transbound Emerg Dis — Glanders in India 2015–18", url: "https://doi.org/10.1111/tbed.13475", kind: "peer-reviewed", access: "abstract" },
  nrce_glanders:     { title: "ICAR-NRCE (WOAH 2023) — Glanders control status in India", url: "https://rr-asia.woah.org/app/uploads/2023/09/glanders-control-status-in-india-challenges-and-opportunity_-final-version.pdf", kind: "extension" },
  yadav2019:         { title: "Yadav et al. 2019, J Equine Vet Sci — Surra (T. evansi) in equines of north and north-west India", url: "https://doi.org/10.1016/j.jevs.2019.05.019", kind: "peer-reviewed", access: "abstract" },
  bhojani2023:       { title: "Bhojani et al. 2023, Indian J Anim Res — Piroplasmosis (T. equi) in Rajasthan horses", url: "https://arccjournals.com/journal/indian-journal-of-animal-research/B-4325", kind: "peer-reviewed", access: "abstract" },
  maharana2026:      { title: "Maharana et al. 2026, Exp Parasitol — Theileria equi in Indian horses (PCR)", url: "https://doi.org/10.1016/j.exppara.2026.109135", kind: "peer-reviewed", access: "abstract" },
  burn2010:          { title: "Burn, Dennison & Whay 2010, Appl Anim Behav Sci — Behaviour and health in working horses, donkeys and mules", url: "https://research.universityofgalway.ie/en/publications/relationships-between-behaviour-and-health-in-working-horses-donk/", kind: "peer-reviewed", access: "abstract" },
  // heat
  holcomb2013:       { title: "Holcomb et al. 2013, J Anim Sci — Horses in shaded vs unshaded pens in hot sun", url: "https://doi.org/10.2527/jas.2013-6497", kind: "peer-reviewed", access: "abstract" },
  pritchard2006:     { title: "Pritchard, Barr & Whay 2006, Equine Vet J — Behavioural measures of heat stress in working equids", url: "https://doi.org/10.2746/042516406778400646", kind: "peer-reviewed", access: "abstract" },
  kang2023:          { title: "Kang et al. 2023, Int J Biometeorol — Heat stress in horses: a review", url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10267279/", kind: "peer-reviewed" },
  rasheed2010:       { title: "Rasheed et al. 2010, J Anim Plant Sci — Anhidrosis in horses (Lahore)", url: "https://thejaps.org.pk/manuscript/2010-japs-211.pdf", kind: "peer-reviewed" },
  ufifas_an362:      { title: "UF/IFAS AN362 — Anhidrosis in the horse (non-sweaters)", url: "https://ask.ifas.ufl.edu/publication/AN362", kind: "extension" },
  johnson2010:       { title: "Johnson et al. 2010, JAVMA — Epidemiology of anhidrosis in Florida (4,620 horses)", url: "https://doi.org/10.2460/javma.236.10.1091", kind: "peer-reviewed", access: "abstract" },
  usef_heat:         { title: "US Equestrian / AAEP — Heat index guidance (°F + % humidity)", url: "https://usef.org/media/press-releases/us-equestrian-competition-update-heat-index", kind: "extension" },
  santana2026:       { title: "Santana & Bignardi 2026, J Anim Breed Genet — THI and WBGT thresholds in 13,960 horses", url: "https://doi.org/10.1111/jbg.70056", kind: "peer-reviewed", access: "abstract" },
  // eating, drinking, elimination, body care
  scheurer2017:      { title: "Scheurer et al. 2017, Agrarforschung Schweiz — Chewing time per kg of hay and feeds", url: "https://www.agrarforschungschweiz.ch/?p=27492", kind: "peer-reviewed" },
  ellis2015:         { title: "Ellis et al. 2015, Appl Anim Behav Sci — Hay nets and night-time budgets of stabled horses", url: "https://irep.ntu.ac.uk/id/eprint/27162/", kind: "peer-reviewed" },
  baumgartner2020:   { title: "Baumgartner et al. 2020, Animals — Night-time gaps without forage in 104 stabled horses", url: "https://doi.org/10.3390/ani10030411", kind: "peer-reviewed" },
  merck_dental:      { title: "Merck Vet Manual — Signs of dental problems in horses", url: "https://www.merckvetmanual.com/multimedia/table/signs-of-dental-problems-in-horses", kind: "vet manual" },
  torcivia2025:      { title: "Torcivia & McDonnell 2025, Animals — A behavioural signature of gastric discomfort?", url: "https://doi.org/10.3390/ani15010088", kind: "peer-reviewed" },
  mcgreevy2001:      { title: "McGreevy et al. 2001, Appl Anim Behav Sci — Geophagia in horses", url: "https://doi.org/10.1016/s0168-1591(00)00173-8", kind: "peer-reviewed", access: "abstract" },
  merck_nutrition:   { title: "Merck Vet Manual — Nutritional requirements of horses (water)", url: "https://www.merckvetmanual.com/management-and-nutrition/nutrition-horses/nutritional-requirements-of-horses", kind: "vet manual" },
  crowell1985:       { title: "Crowell-Davis et al. 1985, J Anim Sci — Feeding and drinking behaviour of mares and foals", url: "https://references.equine-behaviour.de/show.php?record=54", kind: "peer-reviewed", access: "abstract" },
  pritchard2008:     { title: "Pritchard et al. 2008, Equine Vet J — Indicators of dehydration in working horses", url: "https://doi.org/10.2746/042516408x297462", kind: "peer-reviewed", access: "abstract" },
  nyman2001:         { title: "Nyman & Dahlborn 2001, Physiol Behav — Waterer type and flow rate change drinking", url: "https://doi.org/10.1016/s0031-9384(00)00432-7", kind: "peer-reviewed", access: "abstract" },
  barrell2022:       { title: "Barrell 2022, Vet Clin N Am Equine — Polyuria and polydipsia in horses", url: "https://doi.org/10.1016/j.cveq.2021.11.007", kind: "peer-reviewed", access: "abstract" },
  sambraus2003:      { title: "Sambraus & Zeitler-Feicht 2003, Pferdeheilkunde — Urination in open-housed horses", url: "https://portal.fis.tum.de/en/publications/das-harnen-von-pferden-im-offenlaufstall/", kind: "peer-reviewed", access: "abstract" },
  luz2021:           { title: "Luz et al. 2021, Behav Processes — Workload, weather and rolling in horses and mules", url: "https://doi.org/10.1016/j.beproc.2021.104433", kind: "peer-reviewed", access: "abstract" },
  // rest and sleep
  aleman2008:        { title: "Aleman, Williams & Holliday 2008, AAEP — Sleep and sleep disorders in horses", url: "https://www.ivis.org/library/aaep/aaep-annual-convention-san-diego-2008/sleep-and-sleep-disorders-horses", kind: "peer-reviewed" },
  fuchs2017:         { title: "Fuchs et al. 2017 — Equine sleep disorders: 39 horses with collapses (polysomnography)", url: "https://www.ivis.org/library/evc/evc-voorjaarsdagen-hague-2017/polysomnography-and-24-hour-observation-evaluation-of-equine-sleep-disorders-narcolepsy-or-rem-sleep", kind: "peer-reviewed", access: "abstract" },
  raabymagle2006:    { title: "Raabymagle & Ladewig 2006, J Equine Vet Sci — Lying behaviour and box size", url: "https://www.produccion-animal.com.ar/produccion_equinos/curso_equinos_I/14-behavoiur_box_size.pdf", kind: "peer-reviewed" },
  kjellberg2022:     { title: "Kjellberg, Sassner & Yngvesson 2022, Appl Anim Behav Sci — Resting in shelters vs single boxes", url: "https://pub.epsilon.slu.se/id/document/20398953", kind: "peer-reviewed" },
  pedersen2004:      { title: "Pedersen et al. 2004, J Equine Vet Sci — Bedding and time spent lying", url: "https://doi.org/10.1016/j.jevs.2004.03.013", kind: "peer-reviewed", access: "abstract" },
  greening2018:      { title: "Greening 2018, ISAE — Equine nocturnal behaviour and welfare", url: "https://pure.hartpury.ac.uk/en/publications/sleep-vs-no-sleep-equine-nocturnal-behaviour-and-its-implications/", kind: "peer-reviewed", access: "abstract" },
  oliveira2022:      { title: "Oliveira et al. 2022, J Equine Vet Sci — Lying of hospitalised horses (osteoarthritis)", url: "https://doi.org/10.1016/j.jevs.2021.103832", kind: "peer-reviewed", access: "abstract" },
  helmerich2025:     { title: "Helmerich, Bachmann & Gygax 2025, Equine Vet J — Night-to-night lying of young horses", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11616951/", kind: "peer-reviewed" },
  maisonpierre2019:  { title: "Maisonpierre et al. 2019, Equine Vet J — Accelerometer time budgets and day-to-day variation", url: "https://doi.org/10.1111/evj.13130", kind: "peer-reviewed", access: "abstract" },
  // thermal imaging
  jansson2021:       { title: "Jansson et al. 2021, Physiol Behav — Eye temperature by thermography in the field (32 horses)", url: "https://doi.org/10.1016/j.physbeh.2020.113218", kind: "peer-reviewed", access: "abstract" },
  orhun2026:         { title: "Orhun et al. 2026, Equine Vet J — Lacrimal caruncle thermography vs rectal: camera and distance", url: "https://avesis.atauni.edu.tr/yayin/bee4927c-9440-4240-9b61-e8dd0b32e1ac/lacrimal-caruncula-thermography-overestimates-rectal-temperature-in-horses-influence-of-camera-type-and-measurement-distance", kind: "peer-reviewed", access: "abstract" },
  zobrist2024:       { title: "Zobrist et al. 2024, JAVMA — Non-contact infrared thermometers in horses", url: "https://doi.org/10.2460/javma.23.12.0714", kind: "peer-reviewed", access: "abstract" },
  // welfare, communication, social, reproduction
  fureix2012:        { title: "Fureix et al. 2012, PLoS ONE — A depression-like 'withdrawn' state in horses", url: "https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0039280", kind: "peer-reviewed" },
  fureix2011_ears:   { title: "Fureix et al. 2011, ISAE — What do ear positions tell us about horse welfare?", url: "https://hal-univ-rennes1.archives-ouvertes.fr/hal-01318901", kind: "peer-reviewed", access: "abstract" },
  ruet2019:          { title: "Ruet et al. 2019, Animals — Housing horses in individual boxes and welfare", url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6770668/", kind: "peer-reviewed" },
  stomp2018:         { title: "Stomp et al. 2018, PLoS ONE — Snorts as an indicator of positive emotion", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC6040684", kind: "peer-reviewed" },
  briefer2015:       { title: "Briefer et al. 2015, Sci Rep — Whinnies carry emotional valence and arousal", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4404681", kind: "peer-reviewed" },
  yarnell2015:       { title: "Yarnell et al. 2015, Physiol Behav — Social contact, stress hormones and eye temperature", url: "https://irep.ntu.ac.uk/id/eprint/15103/", kind: "peer-reviewed" },
  mcafee2002:        { title: "McAfee, Mills & Cooper 2002 — Mirrors reduce weaving in stabled horses", url: "https://refinementdatabase.org/publications/the-use-of-mirrors-for-the-control-of-stereotypic-weaving-behaviour-in-the-stabled-horse", kind: "peer-reviewed", access: "abstract" },
  schmucker2022:     { title: "Schmucker et al. 2022, PLoS ONE — Moving horses into single stalls: behaviour and immunity", url: "https://doi.org/10.1371/journal.pone.0272445", kind: "peer-reviewed" },
  coleman2004:       { title: "Coleman & Powell 2004, Univ. Kentucky ASC-157 — Teasing mares (oestrus signs)", url: "https://publications.ca.uky.edu/sites/publications.ca.uky.edu/files/asc157.pdf", kind: "extension" },
  zupan2020:         { title: "Zupan et al. 2020, J Appl Anim Welf Sci — Late feeding and horse behaviour", url: "https://doi.org/10.1080/10888705.2019.1663734", kind: "peer-reviewed", access: "abstract" },
  lagos2019:         { title: "Lagos & Tadich 2019, Frontiers Vet Sci — Mules need their own reference values", url: "https://doi.org/10.3389/fvets.2019.00400", kind: "peer-reviewed" },
  // stereotypies, stress, welfare
  sarrafchi2013:     { title: "Sarrafchi & Blokhuis 2013, J Vet Behav — Equine stereotypic behaviours: causes, occurrence, prevention", url: "https://slunik.slu.se/kursfiler/DO0029/40129.1314/Artikel_4._Equine_stereotypic_behaviors_Causation,_occurrence,_and_prevention.pdf", kind: "peer-reviewed" },
  archer2004:        { title: "Archer et al. 2004, JAVMA — Crib-biting and epiploic foramen entrapment colic (68 cases)", url: "https://doi.org/10.2460/javma.2004.224.562", kind: "peer-reviewed", access: "abstract" },
  nicol2002:         { title: "Nicol et al. 2002, Vet Rec — Crib-biting and gastric ulcers in young horses", url: "https://doi.org/10.1136/vr.151.22.658", kind: "peer-reviewed", access: "abstract" },
  wickens2013:       { title: "Wickens et al. 2013, J Equine Vet Sci — Gastric ulcers in adult crib-biters", url: "https://doi.org/10.1016/j.jevs.2012.12.004", kind: "peer-reviewed", access: "abstract" },
  waters2002:        { title: "Waters, Nicol & French 2002, Equine Vet J — How stereotypies start in young horses", url: "https://doi.org/10.2746/042516402776180241", kind: "peer-reviewed", access: "abstract" },
  cooper2000:        { title: "Cooper et al. 2000, Appl Anim Behav Sci — Wider visual horizons reduce weaving", url: "https://doi.org/10.1016/s0168-1591(00)00115-5", kind: "peer-reviewed", access: "abstract" },
  hildebrand2025:    { title: "Hildebrand & Zaleśny 2025, Front Zool — Do stereotypies help or harm? (cortisol review)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12344989", kind: "peer-reviewed" },
  roberts2019:       { title: "Roberts 2019, Vet Med (Auckl) — Trigeminal-mediated headshaking", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC6330979", kind: "peer-reviewed" },
  bell2024:          { title: "Bell et al. 2024, Animals — Headshaking triggers and seasonality (216 horses)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10967644", kind: "peer-reviewed" },
  mcdonnell2008:     { title: "McDonnell 2008, Anim Reprod Sci — Self-mutilation in stallions", url: "https://doi.org/10.1016/j.anireprosci.2008.04.012", kind: "peer-reviewed", access: "abstract" },
  fureix2011_yawn:   { title: "Fureix et al. 2011, ISRN Zoology — Yawning and stereotypic behaviour", url: "https://doi.org/10.5402/2011/271209", kind: "peer-reviewed" },
  merkies2019:       { title: "Merkies et al. 2019, Animals — Blink rate and eyelid twitches under stress", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC6721043/", kind: "peer-reviewed" },
  hintze2016:        { title: "Hintze et al. 2016, PLoS ONE — Eye wrinkles and emotional state", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5061373", kind: "peer-reviewed" },
  travain2021:       { title: "Travain & Valsecchi 2021, Animals — Infrared thermography and emotion: a critical review", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8464846", kind: "peer-reviewed" },
  phelipon2024:      { title: "Phelipon et al. 2024, Front Vet Sci — Forage, movement and contact in sport-horse welfare", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11615640", kind: "peer-reviewed" },
  hausberger2026:    { title: "Hausberger, Lerch & Grandgeorge 2026, Animals — Calm attention and mobility mark good welfare", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC13203647", kind: "peer-reviewed" },
  hallkay2024:       { title: "Hall & Kay 2024, Animal Welfare — Positive and negative welfare indicators: systematic review", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11503716", kind: "peer-reviewed" },
  sommerville2018:   { title: "Sommerville, Brown & Upjohn 2018, PLoS ONE — Brooke SEBWAT welfare tool (71,865 equids)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5821349", kind: "peer-reviewed" },
  czycholl2018:      { title: "Czycholl et al. 2018, Animals — AWIN horse welfare protocol reliability", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5789302", kind: "peer-reviewed" },
  pimenta2026:       { title: "Pimenta et al. 2026, Vet Sci — Behavioural vs physical signs of gastric ulcers", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC13120214", kind: "peer-reviewed" },
  schork2018:        { title: "Schork et al. 2018, PLoS ONE — Welfare of police horses", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC6124763", kind: "peer-reviewed" },
  // foaling
  hartmann2018:      { title: "Hartmann et al. 2018, Reprod Domest Anim — Restlessness before foaling (halter accelerometer)", url: "https://doi.org/10.1111/rda.13250", kind: "peer-reviewed", access: "abstract" },
  jung2022:          { title: "Jung, Chang & Yoon 2022, J Anim Sci Technol — Foaling alarm from behaviour (18 mares)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC9890331/", kind: "peer-reviewed" },
  aoki2023:          { title: "Aoki et al. 2023, PLoS ONE — Tail skin temperature and lying before foaling", url: "https://doi.org/10.1371/journal.pone.0286807", kind: "peer-reviewed" },
  melchert2019:      { title: "Melchert et al. 2019, Theriogenology — Disturbing the mare lengthens delivery", url: "https://doi.org/10.1016/j.theriogenology.2019.02.006", kind: "peer-reviewed", access: "abstract" },
};

export const GROUPS = [
  { key: "colic_pain", name: "Colic & pain" },
  { key: "illness",    name: "Illness & infection" },
  { key: "heat",       name: "Heat & climate" },
  { key: "vices",      name: "Stable vices (stereotypies)" },
  { key: "welfare",    name: "Stress, mood & company" },
  { key: "rest",       name: "Rest & sleep" },
  { key: "feeding",    name: "Eating & drinking" },
  { key: "elimination", name: "Urination & manure" },
  { key: "vitals",     name: "Temperature & breathing" },
  { key: "foaling",    name: "Foaling & foals" },
  { key: "normal",     name: "Normal — don't alarm" },
];

// specificity: strong  — a reliable sign on its own
//              weak    — means little alone; look for clusters
//              normal  — normal behaviour, context for other signs
export const PATTERNS = [
  // ---- colic & pain ------------------------------------------------------ //
  { id: "rolling", group: "colic_pain", name: "Rolling", label: "rolling", specificity: "strong",
    looks: "Goes down and rolls onto the back or side, often repeatedly. Normal dust-bathing is a single roll that ends with the horse getting up and shaking.",
    means: "Highest score (5) on the Equine Acute Abdominal Pain Scale. Rolling from standing that is not dust-bathing needs a person to look now.",
    confuse: "Dust-bathing after work or a bedding change (horses and mules roll after hard work and after a bath, and their body temperature falls after it); a half-roll before getting up after night rest (12–33% of get-ups in boxes); foals and new bedding bring more rolling.",
    equicare: { status: "prototype", how: "'Possible roll': the horse is down, a burst of movement, and its box height swings (our rule; no published video roll detector exists). Our motion test on open clips: rolling median 0.41 vs eating 0.05. Label rolls on footage to validate." },
    sources: ["maskato2020", "merck_colic", "auer2021", "luz2021", "raabymagle2006"] },
  { id: "down_up", group: "colic_pain", name: "Repeatedly lying down and getting up", label: "lies_down", specificity: "strong",
    looks: "Lies down, gets up within minutes, lies down again. The ethogram calls it 'frequent interrupted recumbent rests'.",
    means: "Abdominal pain (colic). The commonest colic sign: attempts to lie down in 77% of 1,016 colic cases; severe, repeated attempts raised the odds of a critical case 12-fold. Normal lying bouts last about 15–40 min.",
    confuse: "A horse settling on new bedding; first nights in a new stall; normal nights hold about 4 get-ups.",
    equicare: { status: "prototype", how: "Lie-down and get-up events from the horse's box shape over time on the colour picture (method validated on dairy cows: 92 % of get-ups, 80–87 % of lie-downs), learned per stall. Needs the optional detector. Watch note at 3+ lie-downs within an hour." },
    threshold: { text: "No published count per hour exists. Our watch note: 3+ lie-downs within an hour.", ours: true },
    sources: ["merck_colic", "torcivia2021", "maskato2020", "psu_colic", "adriaens2022", "curtis2015", "raabymagle2006"] },
  { id: "flank_watching", group: "colic_pain", name: "Flank watching", label: "flank_watching", specificity: "strong",
    looks: "Turns the head back towards the flank or belly and holds it, or does so again and again.",
    means: "Score 1 on EAAPS; repeated flank watching is a strong colic sign.",
    confuse: "Scratching or biting at flies — brief, with the mouth on the coat.",
    equicare: { status: "label", how: "No detector. Label it to teach one." },
    sources: ["maskato2020", "merck_colic"] },
  { id: "kick_belly", group: "colic_pain", name: "Kicking at the belly", label: "kick_at_belly", specificity: "strong",
    looks: "Lifts a hind leg and kicks forward, towards the belly.",
    means: "Score 3 on EAAPS; a strong colic sign.",
    confuse: "Stamping at flies on the legs (foot goes down, not forward under the belly).",
    equicare: { status: "label", how: "No detector. Label it to teach one." },
    sources: ["maskato2020", "merck_colic"] },
  { id: "pawing", group: "colic_pain", name: "Pawing", label: "pawing", specificity: "weak",
    looks: "Scrapes the floor repeatedly with a front hoof.",
    means: "Score 3 on EAAPS when part of a pain picture — but on its own it is common frustration or feed anticipation.",
    confuse: "Waiting for feed (rises in the 20 min before a meal); Merck also lists pawing as a locomotor stereotypy.",
    equicare: { status: "label", how: "No detector. Label it; read it together with the time of the next feed." },
    sources: ["maskato2020", "merck_colic", "mata2024", "merck_behaviour"] },
  { id: "stretch_urinate", group: "colic_pain", name: "Stretching as if to urinate", label: "stretch_as_if_to_urinate", specificity: "strong",
    looks: "Takes the urination stance — hind legs back, body stretched — with effort but no stream, or only a little.",
    means: "Abdominal pain (colic); the ethogram lists the urination stance without a stream as a sign. Frequent small urinations point to bladder stones or cystitis instead.",
    confuse: "Normal urination (a full stream follows).",
    equicare: { status: "label", how: "The floor-patch detector sees urine, not the stance. Label the stance to teach it." },
    sources: ["merck_colic", "torcivia2021", "merck_urolith"] },
  { id: "lateral_awake", group: "colic_pain", name: "Lying flat on the side while awake", label: "lying_lateral", specificity: "strong",
    looks: "Lies flat on the side with the head down but is awake — head lifting, legs moving, or repositioning again and again.",
    means: "Score 4 on EAAPS. Lateral lying is also normal deep (REM) sleep — the difference is that a sleeping horse is still.",
    confuse: "Normal REM sleep: about 30 min a night (22–37), lying still, flat out or on the chest with the head on the ground, mostly 00:00–05:00.",
    equicare: { status: "prototype", how: "'Possibly flat on the side': lying with a longer, lower box than this horse usually lies with — or the detector losing a lying horse, which it does for horses flat out (open-photo test: found 13/14 chest-lying, 0/4 flat). Cannot tell awake from asleep." },
    threshold: { text: "No published time limit. Normal single lying bouts stayed at or under ~57 min; our watch note is 60 min flat in 90 min.", ours: true },
    sources: ["maskato2020", "torcivia2021", "kelemen2021", "zimmer2026"] },
  { id: "restless", group: "colic_pain", name: "Restlessness", label: null, specificity: "weak",
    looks: "Moves about the box more than usual, cannot settle.",
    means: "Score 2 on EAAPS; with other signs it points to pain, alone it may be anticipation or excitement.",
    confuse: "The 20 minutes before a meal; a neighbour leaving; first days in a new stall.",
    equicare: { status: "prototype", how: "Camera activity (colour picture by default), compared with this horse's own 7-day level ('Activity unusual for this horse'). A watch note, never an alarm." },
    sources: ["maskato2020", "mata2024", "auer2021"] },
  { id: "dull_back_of_box", group: "colic_pain", name: "Dull, head low, at the back of the box", label: null, specificity: "weak",
    looks: "Stands away from the door with the head low, not interested in people or surroundings, may lean on the wall.",
    means: "Pain in the box (Ask 2020: position in the box, head position, interest). After severe colic, a quiet horse can mean it is getting worse (endotoxaemia), not better.",
    confuse: "Dozing — relaxed, a hind leg rested, eyes half closed, and it wakes easily. See also 'Withdrawn posture' and 'Facing the wall'.",
    equicare: { status: "prototype", how: "Low activity versus the horse's own level, where in the stall it stood (the stall map), head carriage (the top of the horse's box against its own head-up height) and whether it reacts to people — 'Dull or withdrawn', and the colic 'quiet' sign. Facing is not measured." },
    sources: ["ask2020", "torcivia2021", "merck_colic", "csu_comfort"] },
  { id: "weight_shifting", group: "colic_pain", name: "Frequent weight shifting", label: null, specificity: "weak",
    looks: "Shifts weight from leg to leg again and again while standing.",
    means: "Pain: a median of 2 shifts per hour without pain vs 13 per hour in severe pain.",
    confuse: "Weaving (rhythmic side-to-side with the head and neck); resting a hind leg (normal).",
    equicare: { status: "label", how: "Not detectable at 176×144 px; needs a limb-level model." },
    sources: ["nowak2024"] },
  { id: "rocking_back", group: "colic_pain", name: "Rocking-back stance", label: null, specificity: "strong",
    looks: "Weight on the hind legs with both front feet placed out in front of the body; reluctant to move or get up.",
    means: "Front-foot laminitis — but fewer than 25% of 577 laminitis cases showed it; over 70% showed difficulty turning, a short stilted walk or lameness at walk. Needs a vet: pulses and hoof heat are hands-on checks.",
    confuse: "Parked-out stance to urinate (brief).",
    equicare: { status: "label", how: "Use 'Other' with a note; lameness is measured later by other sensors." },
    sources: ["merck_laminitis", "torcivia2021", "wylie_laminitis"] },
  { id: "pain_face", group: "colic_pain", name: "Pain face (grimace)", label: null, specificity: "weak",
    looks: "Ears stiff and back, tightened eyes, tension above the eye, tense chewing muscles, strained mouth and nostrils.",
    means: "Pain (Horse Grimace Scale 0–12). Observers agree less on face than on body signs, and nostrils agree least.",
    confuse: "Drowsiness, flies, bright light — and stress: transport or being alone brings more eye white, wide nostrils and ear flicking, items that overlap the pain face.",
    equicare: { status: "not_visible", how: "Needs a close, front-on, well-lit face. A stall camera 3–4 m away cannot score it." },
    sources: ["dallacosta2014", "gleerup2015", "vandierendonck2020", "ask2020", "broome2019", "lundblad2021"] },

  // ---- stable vices ------------------------------------------------------ //
  { id: "weaving", group: "vices", name: "Weaving", label: "weaving", specificity: "strong",
    looks: "Obvious side-to-side swaying of the head, neck and forequarters, sometimes the hindquarters, in the same spot — often at the stall front.",
    means: "A stereotypy (about 3% of horses; 4.6% of young horses, starting around 15 months) linked to confinement, little social contact and grain-heavy diets. Mostly before the morning feed and before turnout. Cortisol studies point both ways (7 of 21 higher, 6 lower), so it is a management flag — a lasting trace of conditions, not proof of distress now. Blocking it (anti-weave bars) moves it further into the stall; sight and touch of a neighbour, or a mirror, reduce it.",
    confuse: "Weight shifting from pain (not rhythmic); restlessness at the door before meals.",
    equicare: { status: "prototype", how: "A regular, persistent, mostly sideways rhythm of the moving mass, 0.25–2 Hz, on the colour picture — the tracking + periodicity method a zoo study used for stereotypic pacing (96.7 % precision). Reported as minutes per day and episodes, against the horse's own level." },
    threshold: { text: "No peer-reviewed source gives a weaving frequency or minimum cycle count (the '30–90 swings a minute' often quoted is from a commercial website). We search 0.25–2 Hz and join bouts under 10 min apart (Sambraus 1989: 67 min/day on average in 27 weavers).", ours: true },
    sources: ["hausberger2009", "merck_behaviour", "ufifas_vm257", "brauns2025", "cortisol2024", "yang2025", "sarrafchi2013", "waters2002", "cooper2000", "hildebrand2025", "mcafee2002"] },
  { id: "crib_biting", group: "vices", name: "Crib-biting / wind-sucking", label: "crib_biting", specificity: "strong",
    looks: "Grips a fixed edge (door, manger) with the front teeth, arches the neck, pulls back and gulps air, often with a grunt. Wind-sucking is the same without gripping anything.",
    means: "A stereotypy in 2.4–8.3% of horses (13% of Thoroughbreds); established cribbers crib about 1,500 times a day. Strongly linked to one type of colic (epiploic foramen entrapment: odds 34.7×, one hospital) — watch a cribber closely for colic. The ulcer link holds in foals, not in adult cribbers on pasture. Concentrate after weaning raised the risk 4×. Usually after concentrate feed (one study: before and during the afternoon feed). Once established it persists; few horses copy it from a neighbour (about 1%).",
    confuse: "Normal chewing of wood or the feeder — no arch, no grunt.",
    equicare: { status: "label", how: "No detector (would need a model or a microphone). Label it to teach one." },
    sources: ["hausberger2009", "merck_behaviour", "ufifas_vm257", "mazzola2016", "sarrafchi2013", "archer2004", "nicol2002", "wickens2013"] },
  { id: "box_walking", group: "vices", name: "Box walking", label: "box_walking", specificity: "strong",
    looks: "Walks the stall perimeter again and again. Two kinds: slow, silent circling, or fast walking with neighing.",
    means: "About 2% of horses. The fast, calling kind means confinement distress; if it happens only when a neighbour leaves, separation anxiety. A mirror reduced it in a small study.",
    confuse: "A new horse exploring; anticipation before feed.",
    equicare: { status: "prototype", how: "Laps of the stall: a slow (7–30 s), wide back-and-forth of where the movement is while the horse stays busy. No published kinematics — our rule." },
    sources: ["merck_behaviour", "ufifas_vm257", "sarrafchi2013", "waters2002"] },
  { id: "head_tossing", group: "vices", name: "Head nodding / tossing", label: "head_tossing", specificity: "weak",
    looks: "Repetitive up-and-down bobbing of the head, or sudden bouts of tossing.",
    means: "May be a stereotypy — but head shaking has medical causes too. Trigeminal headshaking (nerve pain in the face, about 1% of horses) shows as sudden up-and-down flicks with nose rubbing or snorting; owners named bright sunlight as the trigger in 61% and a season in 54%. A camera cannot tell which: a vet should see a new head-shaker, especially one that is worse in sun.",
    confuse: "Tossing at flies; nodding before feeds (anticipation).",
    equicare: { status: "prototype", how: "A regular up-down rhythm while the horse stays in place (a walking horse nods with each stride). Irregular tossing is not counted — that points to discomfort or flies." },
    sources: ["hausberger2009", "merck_behaviour", "roberts2019", "bell2024"] },
  { id: "vice_timing", group: "vices", name: "When vices happen", label: null, specificity: "normal",
    looks: "Weaving, nodding, pawing and door kicking build up before feeds and before turnout: in ration-fed horses from 2.2 events (41–60 min before) to 7.2 in the last 20 min. Crib-biting usually follows a concentrate meal.",
    means: "A build-up before feeds is itself a sign of restricted forage — horses with hay always available showed none. More vice time suggests more stress or a feeding change; fix the cause (forage, contact, exercise) rather than block the behaviour.",
    confuse: "Prevalence depends on how you look: 1–2% on short farm visits, 4–5% oral stereotypies, 32% of Colombian stabled horses, 86% of boxed sport horses once minor oral habits count. Continuous video sees more than a visit.",
    equicare: { status: "prototype", how: "Weaving events are time-stamped; feed times are not linked yet." },
    sources: ["mata2024", "mazzola2016", "ufifas_vm257", "mejia2022", "sarrafchi2013", "czycholl2018", "hausberger2009"] },

  { id: "eating_time", group: "feeding", name: "Eating time", label: "eating", specificity: "normal",
    looks: "Head at hay, manger or floor, chewing.",
    means: "Set by the ration: hay takes about 33 min per kg (2,600 chews), concentrate 12–16 min per kg. Stabled horses on set rations eat as little as 3–4 h a day; 8.7 h in 80 stalled cavalry horses; 8–14 h grazing. Pain lowers it: horses in severe pain ate 34% of the time vs 48%, in 2 bouts an hour instead of 5. A drop against the horse's own level matters more than the number.",
    confuse: "Mouthing bedding or chewing wood; a new hay net (small holes add about 5 min per kg).",
    equicare: { status: "prototype", how: "Seconds per minute with the head at the hay, where a hay box is marked on the colour picture (time, not amount; amount needs the feeder sensor)." },
    sources: ["merck_behaviour", "griffin2019", "ogilvie1994", "auer2021", "scheurer2017", "ellis2015", "nowak2024"] },
  { id: "drinking_time", group: "feeding", name: "Drinking", label: "drinking", specificity: "normal",
    looks: "Muzzle in the water, swallowing.",
    means: "At least 5 L per 100 kg a day — 21–29 L for a 500 kg horse on a mixed ration, about double on hay only, over 70 L after work in heat. Normal 25–70 mL/kg a day; over 100 mL/kg is too much (kidney disease, PPID, or boredom). Mares at 30–35 °C drank about 13 times a day, least 05:00–09:00, most 13:00–17:00; a stall camera study saw peaks 16:00–22:00. A dehydrated horse drinks more often and for longer — the best field sign in working horses at 30–44 °C. Too little water raises the risk of impaction colic.",
    confuse: "Playing with the water. Slow-filling bowls cut intake (bucket 58, slow bowl 43 mL/kg a day) and horses chose buckets for 98% of their water.",
    equicare: { status: "sensor", how: "Litres need the flow meter. The camera could count visits to the trough, where the trough is in view (not built)." },
    sources: ["giannone2026", "williams2015", "merck_nutrition", "crowell1985", "pritchard2008", "nyman2001", "barrell2022"] },

  // ---- rest & sleep ------------------------------------------------------ //
  { id: "normal_lying", group: "rest", name: "Lying down (normal)", label: "lying", specificity: "normal",
    looks: "Lies on the chest (sternal), legs folded; or flat on the side for deep sleep.",
    means: "Normal rest — and the range is wide. Measured daily totals: 25 ± 22 min (accelerometers, Lipizzaners), 67 ± 62 min (0–319, 83 horses), 90 min in 80 stalled cavalry horses, 135–145 min on video in single boxes (lateral about a third of it). Night rest runs about 21:00–06:00, the longest bouts 00:00–04:00, in 1–7 bouts of 10–40 min. Horses differ far more from each other than one horse differs night to night, so each horse's own level is the yardstick. More lying on straw (lateral 3× longer) and in bigger boxes.",
    confuse: "—",
    equicare: { status: "prototype", how: "Lying minutes, bouts and the longest bout from the horse's box on the colour picture, once the stall's standing and lying shapes are learned (optional detector). Stillness alone is not lying." },
    sources: ["auer2021", "kelemen2021", "gobbo2025", "ogilvie1994", "zimmer2026", "adriaens2022", "kjellberg2022", "raabymagle2006", "pedersen2004"] },
  { id: "rem_deprivation", group: "rest", name: "Too little lying (REM deprivation)", label: null, specificity: "strong",
    looks: "Falls asleep standing and buckles at the knees; scrapes on the front of the knees and front fetlocks.",
    means: "REM sleep (about 30 min a night) needs the horse lying — flat, or on the chest with the head on the ground. The '30 min of lying a day' minimum is an assumption, not a measured line: in one study 29 of 83 horses lay under 30 min but only 8 showed signs (they lay ~8 min a day). The collapses decide it: up to 199 a day in one series, 87% of them in REM while standing, mostly at night; knees injured in 72%, fetlocks in 68%. Signs appear after about 10 days to 4 weeks. Causes: pain, insecurity, a too-small stall, a new place or companions, extreme temperatures, illness. Once fixed, horses oversleep at first and are normal within days.",
    confuse: "A new stall (lying is suppressed for the first nights to weeks); normal dozing (the horse sways but does not drop).",
    equicare: { status: "prototype", how: "Watch note after 3 nights the camera saw (6 h+ each) with under 10 min lying. Collapses themselves are not detected yet." },
    sources: ["kelemen2021", "zimmer2026", "burla2017", "fuchs2017", "aleman2008"] },
  { id: "standing_rest", group: "rest", name: "Dozing standing up", label: "standing_still", specificity: "normal",
    looks: "Stands still, head lowered, eyes half closed, one hind leg resting on the toe.",
    means: "Normal: adults take most of their rest standing (about 80% in some studies; 4.5 h a day resting a hind leg in 80 stalled cavalry horses). Resting a hind leg is normal, and healthy horses rest both hinds about equally; always resting the same hind (62:38 in hind-lame horses) points to lameness. Pointing a front leg for long is not normal.",
    confuse: "A dull, painful horse (head low but tense, no hind leg rested, not interested when approached).",
    equicare: { status: "prototype", how: "Counted as 'still' minutes — stillness, not lying." },
    sources: ["auer2021", "torcivia2021", "ogilvie1994", "uellendahl2024"] },

  // ---- urination & manure ----------------------------------------------- //
  { id: "manure_frequency", group: "elimination", name: "Manure frequency", label: "defecating", specificity: "normal",
    looks: "Tail lifted, droppings passed — 4 to 13 times a day for a 1,000 lb horse.",
    means: "Fewer droppings is a colic sign, as is straining — and 'eating less and passing fewer droppings' is the commonest early sign of colic, often without the classic ones. Moving from pasture to a stable more than halved faecal output in one study (drier droppings), mostly in the first 5 days — a known colic-risk window; a change of feed or housing is the best-evidenced colic risk factor.",
    confuse: "—",
    equicare: { status: "prototype", how: "In the colour picture, where a floor box is drawn over bedding: a new compact, dark, textured pile on the bedding after the horse moves away. Where the floor is also in the thermal view: a new warm patch classified by how it cools (the method a mouse study used: F1 0.90 for faeces); both together count as confirmed. Notes: 12 h without manure, or under half the horse's usual daily count." },
    threshold: { text: "No source gives a 'no manure for X hours' alarm. Ours: 12 h, or under 50 % of the horse's own daily count — and always check when it last ate (fasting cuts output 55–63 %).", ours: true },
    sources: ["rutgers_manure", "lpelc", "merck_colic", "williams2015", "outouil2026", "deeposit2025", "react"] },
  { id: "urination", group: "elimination", name: "Urination", label: "urinating", specificity: "normal",
    looks: "Stretched stance, stream of urine; 15–30 mL per kg a day in total (7–14 L for 450 kg), about 5 times a day (4–15), mostly after eating roughage.",
    means: "Frequent small urinations, straining, dribbling or blood point to bladder stones or cystitis (vet). The stance without a stream is a colic sign. Red or brown urine needs a vet: in India it points to piroplasmosis (Theileria equi found in about 1 in 5 horses tested; red urine raised the odds 5×).",
    confuse: "—",
    equicare: { status: "prototype", how: "In the colour picture: bedding going darker where it is wet, a wider smooth patch (shows well on shavings, poorly on straw). In the thermal view, if the floor is in it: a warm patch that cools within minutes (split set by the floor cooling test). 'No urination seen' note only when urination has been seen here in the last 3 days. The stance itself is not detected." },
    threshold: { text: "Counts per day come from small studies (5.5 a day in open housing; 4–15 overall). A 'no urination for X hours' line is not published — our 8 h note is our choice.", ours: true },
    sources: ["rutgers_manure", "lpelc", "merck_urolith", "merck_colic", "deeposit2025", "sambraus2003", "barrell2022", "maharana2026", "bhojani2023"] },

  // ---- vitals ------------------------------------------------------------ //
  { id: "eye_temperature", group: "vitals", name: "Eye temperature (thermal camera)", label: null, specificity: "weak",
    looks: "The hottest point in the eye corner, read by the thermal camera.",
    means: "Not a fever reading. Studies disagree even on the offset from rectal temperature: about 2 °C below (no correlation, Thailand), 0.2 °C below with a thermometer at 6 cm, and 3–5 °C above at the eye corner from 0.5–2 m, the error growing with distance. Month, farm and breed shift it by up to 2.4 °C; field readings did not track rectal temperature at rest; a close-range eye thermometer caught only half of fevers. Stress (transport) raises it 0.5–2 °C for minutes to hours, and horses kept without company read warmer. Use it only as each horse's own trend at the same hour, out of the sun and not after work — and confirm a fever with a rectal thermometer.",
    confuse: "Sun, heat, exercise (raised for 2 h), stress, water sprays, sweat, humidity, a cold stall, distance and viewing angle all change the reading.",
    equicare: { status: "measured", how: "The eye box's hottest pixel — or, when the head is elsewhere in the thermal view, the hottest eye-like point on it (33–41 °C, with warm head around it). Alerts compare with this horse's own 7-day baseline: +1.0 °C watch, +1.5 °C alert. Before 3 days of baseline only a reading at the rectal fever line (38.6 °C) alerts." },
    threshold: { text: "The +1.0 / +1.5 °C steps are our choice; no published eye-temperature threshold exists.", ours: true },
    sources: ["lampang2023", "transport_eye2024", "alberghina2025", "jansson2021", "orhun2026", "zobrist2024", "travain2021", "yarnell2015"] },
  { id: "rectal_temperature", group: "vitals", name: "Rectal temperature (reference)", label: null, specificity: "normal",
    looks: "Contact thermometer.",
    means: "Adults 37.2–38.6 °C (Merck: mares 37.3–38.2, stallions 37.2–38.1). Newborn foals 37.7–38.8 °C. Above 40.5 °C is overheating.",
    confuse: "Heat, exercise and excitement raise it for a while.",
    equicare: { status: "sensor", how: "Enter contact readings; they are judged against this band." },
    sources: ["merck_temp_table", "ext_tpr", "psu_healthy", "merck_emergency"] },
  { id: "resp_rate", group: "vitals", name: "Breathing rate at rest", label: null, specificity: "weak",
    looks: "Breaths per minute, from the nostril warming and cooling or the flank rising and falling.",
    means: "Adults: 10–14 (Merck), 8–12 or 10–24 (extension sources disagree). Foals: 60–80 newborn, 20–40 older. Heat alone raises it: 20.5 a minute in shade vs 25.5 in sun at 30.6 °C. A raised rate comes with pain, fever, heat or distension — a reason to look, not a diagnosis.",
    confuse: "Heat, exercise, excitement.",
    equicare: { status: "measured", how: "Nostril box on the thermal video, referenced to the skin around it, only over 30 s+ with the head still, and only when the rate agrees with a count of breaths; fast breathing (panting) is reported as fast, not folded to a normal-looking rate. Optional flank box on the colour picture as a second opinion. Watch at 20 bpm, alert at 24." },
    sources: ["merck_resp_table", "ext_tpr", "psu_healthy", "rutgers_tpr", "merck_resp", "holcomb2013"] },
  { id: "laboured_breathing", group: "vitals", name: "Laboured breathing", label: null, specificity: "strong",
    looks: "Flared nostrils, fast breathing, a pushed breath out using the belly muscles; over time a 'heave line' along the flank.",
    means: "Airway disease such as heaves (recurrent airway obstruction) — vet.",
    confuse: "Blowing after exercise.",
    equicare: { status: "prototype", how: "Breathing regularity from the nostril signal; effort is not measured." },
    sources: ["merck_heaves", "merck_resp"] },

  // ---- foaling & foals --------------------------------------------------- //
  { id: "foaling_stage1", group: "foaling", name: "Foaling, stage 1", label: null, specificity: "weak",
    looks: "1–4 h of restlessness, sweating on the flanks and behind the elbows, lying down and getting up, rolling, frequent small droppings or urine. Most mares foal at night.",
    means: "Early labour — it looks exactly like colic, so a mare near her due date needs the due date on screen. Waxing is unreliable for timing (70–95% of mares, 6–48 h before).",
    confuse: "Colic.",
    equicare: { status: "label", how: "Label on footage; the breeding module holds due dates." },
    sources: ["merck_parturition", "csu_foaling", "merck_perinatal"] },
  { id: "foaling_stage2", group: "foaling", name: "Foaling, stage 2 (delivery)", label: null, specificity: "strong",
    looks: "Waters break; the mare lies down and strains; the foal is delivered.",
    means: "Normally 10–20 min (average 17). Call the vet if the foal is not out 15–20 min after the waters break (Merck: 30 min).",
    confuse: "—",
    equicare: { status: "label", how: "No detector." },
    sources: ["csu_foaling", "merck_parturition"] },
  { id: "foaling_stage3", group: "foaling", name: "Placenta (stage 3)", label: null, specificity: "strong",
    looks: "The placenta is passed, usually 45–90 min after the foal.",
    means: "Retained if longer than 3 h — vet.",
    confuse: "—",
    equicare: { status: "label", how: "No detector." },
    sources: ["csu_foaling", "merck_perinatal"] },
  { id: "foal_milestones", group: "foaling", name: "Newborn foal milestones", label: "nursing", specificity: "strong",
    looks: "Lies on its chest, stands, finds the udder and suckles.",
    means: "On its chest within 1 h, standing within 2 h, nursing within 3 h — missing one needs the vet. Suckling 5–7 times an hour in week 1, about once an hour by one month (extension sources only).",
    confuse: "Nuzzling the udder without swallowing.",
    equicare: { status: "label", how: "Label 'Nursing'; no detector yet." },
    sources: ["merck_perinatal"] },
  { id: "foal_lying", group: "foaling", name: "Foals lying a lot", label: null, specificity: "normal",
    looks: "Foals lie flat out often and for long.",
    means: "Normal: stalled foals lie 52–56% of the day, in 15–27 bouts, 39–48% of it flat on the side.",
    confuse: "A sick foal (does not get up to nurse).",
    equicare: { status: "sensor", how: "Adult lying rules must not be applied to foals." },
    sources: ["murase2018", "kelemen2021"] },

  // ---- normal — don't alarm --------------------------------------------- //
  { id: "pre_feed", group: "normal", name: "Busy before feeding", label: null, specificity: "normal",
    looks: "Walking, pawing, head shaking, calling and tail swishing in the last 20 min before a set feed.",
    means: "Normal anticipation, strongest in ration-fed horses; a feed an hour late brought more pawing and door kicking. Keeping feed times regular reduces it.",
    confuse: "Restlessness from colic (continues after feeding, and the horse does not eat).",
    equicare: { status: "prototype", how: "Shows as higher activity; feed times are not linked yet." },
    sources: ["mata2024", "zupan2020"] },
  { id: "day_night", group: "normal", name: "Day busy, night quiet", label: null, specificity: "normal",
    looks: "More activity 06:30–18:30; lying and sleep cluster 00:00–06:00; most eating by day.",
    means: "Normal daily rhythm.",
    confuse: "—",
    equicare: { status: "prototype", how: "Activity baselines cover whole days, so the rhythm is included." },
    sources: ["auer2021", "zimmer2026", "kjellberg2021"] },
  { id: "new_place", group: "normal", name: "New stall, first nights", label: null, specificity: "normal",
    looks: "Lies down little and sleeps poorly.",
    means: "Normal: REM sleep is suppressed on night 1 and recovers over nights 1–4; some horses do not lie down at all for a few days; in hospital, lateral lying returned only after day 4; lying rose from 5% of the night in week 1 to 16% by week 6. Moving into a single stall disturbed behaviour for a week and changed immune cells. Give a moved or transported horse 1–2 weeks before judging its baseline.",
    confuse: "REM deprivation (lasts longer, with buckling).",
    equicare: { status: "prototype", how: "Baselines need 3 days before judging 'unusual' activity." },
    threshold: { text: "The 1–2 week settling period is our reading of these studies; none sets a number.", ours: true },
    sources: ["zimmer2026", "oliveira2022", "greening2018", "schmucker2022", "raabymagle2006"] },
  { id: "age_company", group: "normal", name: "Age, company and bedding", label: null, specificity: "normal",
    looks: "Older horses (18+) lie down less often and more briefly; horses in groups lie together at night; more bedded space means more lying.",
    means: "Each horse's own baseline matters more than a population number. Age effects disagree (younger horses lie more in some studies; no effect in others). Mules need their own reference values, separate from horses and donkeys. No behaviour data exist for Marwari, Kathiawari or Indian country-bred horses.",
    confuse: "—",
    equicare: { status: "prototype", how: "All behaviour notes compare the horse with itself." },
    sources: ["zimmer2026", "gobbo2025", "kjellberg2021", "burla2017", "kelemen2021", "lagos2019"] },
  // ==== added 2026-10-04 from the deep research (six reviews) ============== //
  // ---- colic & pain ------------------------------------------------------ //
  { id: "colic_quiet", group: "colic_pain", name: "Quiet colic: eating less, fewer droppings", label: null, specificity: "strong",
    looks: "Leaves hay, passes fewer droppings, stands quiet or dull, lies down more — without rolling, pawing or flank watching.",
    means: "The commonest early picture of colic (REACT campaign). Classic signs are often missing: in 1,016 colic cases flank watching was seen in 68% and kicking at the belly in 43%. Only 9% of owners felt sure they would recognise mild colic, and fewer than half would call a vet for dullness or brief rolling.",
    confuse: "A hot afternoon (heat cuts eating late, not early), a feed change, a new stall, a horse that has just been fed less.",
    equicare: { status: "prototype", how: "Each part is measured against the horse's own level: eating time at the hay, droppings on the floor, lying and activity. Not yet combined into one alert. A leg tag would add a validated route (induced colic detected with 91% accuracy from two leg accelerometers)." },
    threshold: { text: "No study gives how many hours before natural colic these change. Combining two or more against the horse's own level is our choice.", ours: true },
    sources: ["react", "bowden2019", "curtis2015", "eerdekens2024"] },
  { id: "colic_sweating", group: "colic_pain", name: "Sweating with pain signs", label: null, specificity: "strong",
    looks: "Dark wet patches on the neck, flanks or behind the elbows while standing in the stall, together with any pain sign.",
    means: "Severe sweating raised the odds of a critical colic (surgery, hospital or death) 20.7-fold — the strongest single sign in 1,016 cases. Sweating at all was seen in 44% of colic cases.",
    confuse: "Heat, work, excitement, tying-up, a mare foaling (sweats behind the elbows in stage 1).",
    equicare: { status: "label", how: "No detector. Dark wet coat may show in colour; a cooling (evaporating) coat in the thermal view is an untested idea." },
    sources: ["curtis2015"] },
  { id: "pain_hidden", group: "colic_pain", name: "Pain hides when people are there", label: null, specificity: "normal",
    looks: "A horse in discomfort stops showing it when a person comes to the stall.",
    means: "Discomfort behaviours fell from 1.65 to 0.40 a minute during caretaker visits (a 77% drop) and stopped completely in 30% of horses. Unwatched video shows what a visit does not — the reason for a stall camera.",
    confuse: "—",
    equicare: { status: "prototype", how: "People at the stall are found by the detector; their minutes are marked and stall vices are not scored while people are there." },
    sources: ["torcivia2020", "torcivia2021"] },
  { id: "same_hind", group: "colic_pain", name: "Always resting the same hind leg", label: null, specificity: "weak",
    looks: "Over hours, the horse rests (cocks) one particular hind leg far more than the other.",
    means: "Healthy horses rest both hinds about equally; horses lame behind rested the lame leg 62% of the time and lay down more at night (13% vs 3%, one study). The ratio tracked the vet's lameness score.",
    confuse: "Resting a hind leg itself is normal dozing.",
    equicare: { status: "label", how: "Not detected; needs leg-level detail or the leg tag." },
    sources: ["uellendahl2024"] },
  { id: "pointing_fore", group: "colic_pain", name: "Pointing a front leg", label: null, specificity: "weak",
    looks: "Stands with one front foot placed forward and held there, often swapping feet.",
    means: "Abnormal (unlike resting a hind leg): heel pain, navicular disease, laminitis. A discomfort-ethogram item.",
    confuse: "A brief step while eating.",
    equicare: { status: "label", how: "Not detected." },
    sources: ["torcivia2021", "merck_laminitis"] },
  { id: "laminitis_early", group: "colic_pain", name: "Reluctant to turn or move", label: null, specificity: "strong",
    looks: "Turns stiffly or not at all, short stilted steps, moves less round the stall, lies down more.",
    means: "Early laminitis: over 70% of 577 cases showed difficulty turning, a stilted walk or lameness at walk — far more than the classic rocked-back stance (under 25%). Vet now.",
    confuse: "Stiffness after hard work; tying-up; an old horse at the start of the day.",
    equicare: { status: "prototype", how: "Moving time, changes of place and lying against the horse's own level (the night report counts them). Turning itself is not measured." },
    sources: ["wylie_laminitis", "merck_laminitis"] },
  { id: "facing_wall", group: "colic_pain", name: "Facing the wall, head below the withers", label: null, specificity: "weak",
    looks: "Stands in one place facing a back or side wall or a corner, head at or below the withers, bedding undisturbed.",
    means: "Pain or illness on the Colorado State comfort scale (score 3–4), and part of a published chronic-stress score.",
    confuse: "Dozing (hind leg rested, eyes half closed); eating from a wall feeder.",
    equicare: { status: "label", how: "Where in the stall is measured (stall map); which way the head points is not." },
    sources: ["csu_comfort", "stomp2018"] },
  { id: "tying_up", group: "colic_pain", name: "Stiff, sweating, won't move after work", label: null, specificity: "strong",
    looks: "Soon after work: camped-out stance, tucked-up belly, sweating, muscle tremors, refuses to move; may paw or roll; dark urine.",
    means: "Tying-up (exertional rhabdomyolysis). Vet now; do not walk the horse.",
    confuse: "Colic; laminitis.",
    equicare: { status: "label", how: "Not detected." },
    sources: ["merck_exertional"] },

  // ---- illness & infection ------------------------------------------------ //
  { id: "fever_first", group: "illness", name: "Fever before other signs", label: null, specificity: "weak",
    looks: "A rise in temperature, then dullness, eating less, nasal discharge, swelling under the jaw or a cough a day or two later.",
    means: "Strangles: fever of 39.4–41.1 °C comes 24–48 h before other signs, and before the horse sheds the infection. Equine influenza: fever up to 41.1 °C 1–3 days after exposure, cough early. Isolate the horse and call the vet.",
    confuse: "Heat, exercise and stress also warm the eye reading.",
    equicare: { status: "measured", how: "Eye temperature against the horse's own 7-day level (+1.0 °C watch, +1.5 °C alert) — a prompt to take a rectal temperature, not a diagnosis." },
    sources: ["merck_strangles", "msd_influenza"] },
  { id: "after_transport", group: "illness", name: "Dull and feverish after a long journey", label: null, specificity: "strong",
    looks: "Within a week of transport: dull, eating less, fever, mild colic-like signs; then stands braced with elbows out, won't lie down or turn, breathes fast and shallow.",
    means: "Pleuropneumonia ('shipping fever'): long-distance transport is the main risk factor. Vet now; survival 40–90%.",
    confuse: "Colic; settling-in after a move (no fever).",
    equicare: { status: "label", how: "Not detected; eye temperature and breathing rate may rise." },
    sources: ["msd_pleuro"] },
  { id: "cough", group: "illness", name: "Coughing", label: null, specificity: "weak",
    looks: "Coughs, alone or in clusters — at feeding, when bedding is moved, or through the day.",
    means: "Cough frequency is a sensitive sign of airway inflammation (dust, asthma, infection). A cluster across several stalls needs the vet: in India, equine influenza spread across 11+ states in 2008–09, and glanders is notifiable (higher-risk in Uttar Pradesh; Army horses have historically stayed free under surveillance).",
    confuse: "A single cough at dusty hay.",
    equicare: { status: "sensor", how: "Needs a microphone (audio counts agreed with video counts over 97% of the time)." },
    sources: ["duz2010", "virmani2010", "singha2020", "nrce_glanders"] },
  { id: "india_parasites", group: "illness", name: "Dull, thin, eating less (blood parasites)", label: null, specificity: "weak",
    looks: "Gradual dullness, weight loss, poor appetite, sometimes fever and red-brown urine.",
    means: "In India: surra (Trypanosoma evansi) in about 5% of equines of the north, highest after the monsoon (Sep–Nov); piroplasmosis (Theileria equi) common in Rajasthan (half had antibodies, few were ill). Behaviour cannot diagnose them — it can send a horse for a blood test.",
    confuse: "Poor feed, worms, heat, dental trouble.",
    equicare: { status: "label", how: "Shows only as a slow fall in eating time and activity against the horse's own level." },
    sources: ["yadav2019", "bhojani2023"] },
  { id: "unresponsive", group: "illness", name: "Not interested in surroundings", label: null, specificity: "weak",
    looks: "Does not turn the head or ears towards the door, feed cart or people; apathetic.",
    means: "Sickness behaviour, exhaustion or chronic poor welfare. In 10,843 working equids apathy went with poor body condition, wounds, eye problems and age. Brooke's welfare tool (used in India) scores attitude as alert, apathetic or severely depressed. Horses boxed longer were more often unresponsive.",
    confuse: "Dozing; a calm, settled horse.",
    equicare: { status: "label", how: "Not measured; would need the head's reaction to events at the door." },
    sources: ["burn2010", "sommerville2018", "ruet2019"] },

  // ---- heat & climate ----------------------------------------------------- //
  { id: "heat_stress", group: "heat", name: "Heat stress", label: null, specificity: "weak",
    looks: "Faster, deeper breathing, flared nostrils, head nodding, dull; standing by the water; sweating.",
    means: "At 30.6 °C, horses without shade breathed 25.5 vs 20.5 a minute, sweated in 51% vs 1% of checks and spent 34% vs 20% of time near water; body changes came at 12:30, behaviour later. Working equids with these signs had higher rectal temperatures. Eating fell only late. Comfort range 5–25 °C.",
    confuse: "Exercise, excitement, fever, airway disease.",
    equicare: { status: "prototype", how: "Breathing rate is measured; time at the water and the stall's temperature are not yet." },
    sources: ["holcomb2013", "pritchard2006", "kang2023"] },
  { id: "anhidrosis", group: "heat", name: "Not sweating in heat (anhidrosis)", label: null, specificity: "strong",
    looks: "Fast breathing at rest that does not settle, little or no sweat after work (maybe only under the mane), dry harsh coat, hair loss on the face, chest or croup; drinks and eats less.",
    means: "Anhidrosis: 12% of 290 horses in Lahore (peak in July), 2% in Florida, 6–25% of Florida Thoroughbreds over a career. Severe cases collapse. Cool the horse and call the vet. No Indian prevalence study exists.",
    confuse: "Heat stress in a horse that sweats normally; fever.",
    equicare: { status: "label", how: "Not detected. A hot, dry coat in the thermal view after work is a screening idea, not yet tested." },
    sources: ["rasheed2010", "ufifas_an362", "johnson2010"] },
  { id: "heat_stroke", group: "heat", name: "Heat stroke", label: null, specificity: "strong",
    looks: "Dull, weak, head low, reluctant to move, very fast breathing, hot dry skin.",
    means: "Body temperature 41–43 °C. An emergency: cool now and call the vet.",
    confuse: "Colic; tying-up.",
    equicare: { status: "label", how: "Breathing rate and eye temperature may rise; no alert built for it." },
    sources: ["kang2023", "merck_emergency"] },
  { id: "heat_index", group: "heat", name: "Hot, humid stable", label: null, specificity: "normal",
    looks: "Air temperature and humidity in the stall.",
    means: "Vets' rule of thumb (°F + % humidity): under 130 fine, 130–150 watch, 150–180 critical. 34 °C (93 °F) at 50–60% humidity gives 143–153. Performance fell above a temperature-humidity index of 74.7 in 13,960 horses. On hot days, judge breathing and eye temperature against hot-day levels, not cool-day ones.",
    confuse: "—",
    equicare: { status: "sensor", how: "Needs a stall temperature and humidity sensor." },
    sources: ["usef_heat", "santana2026"] },

  // ---- eating & drinking -------------------------------------------------- //
  { id: "meal_length", group: "feeding", name: "Slow meals or feed left", label: null, specificity: "weak",
    looks: "A meal takes much longer than this horse usually takes, or hay is left at the next feed.",
    means: "Expected meal time follows the ration (about 33 min per kg of hay, 12–16 min per kg of concentrate; hay nets slow it). Slower eating or leftovers point to dental pain, fever, colic onset or heat.",
    confuse: "A new hay net or feeder; a bigger ration; a hot afternoon.",
    equicare: { status: "prototype", how: "Eating time at the hay against the horse's own level; feed times and ration weights are not linked yet." },
    threshold: { text: "No published line. Ours: a meal taking more than 1.5× the horse's own usual time.", ours: true },
    sources: ["scheurer2017", "ellis2015", "nowak2024"] },
  { id: "night_forage_gap", group: "feeding", name: "Long night without forage", label: null, specificity: "weak",
    looks: "The longest stretch of the night with no eating.",
    means: "74% of 104 stabled horses on shavings went more than 4 h without forage at night (longest about 8 h 50 min); horses on straw nibbled bedding. Long gaps are linked to ulcers and colic. A gap that includes a normal lying bout is expected.",
    confuse: "Lying down and sleeping (gap is normal then).",
    equicare: { status: "prototype", how: "The night report gives the longest stretch without eating." },
    sources: ["baumgartner2020"] },
  { id: "quidding", group: "feeding", name: "Dropping chewed feed (quidding)", label: null, specificity: "weak",
    looks: "Balls of half-chewed hay dropped near the feeder, slow eating, head tilted while chewing.",
    means: "Dental or mouth pain — the signs that went away most often after infected cheek teeth were removed. Dentist or vet, not urgent.",
    confuse: "A horse pulling hay out of a net onto the floor.",
    equicare: { status: "label", how: "Not detected." },
    sources: ["merck_dental"] },
  { id: "gastric_signs", group: "feeding", name: "Gastric discomfort around meals", label: null, specificity: "weak",
    looks: "Picky eating, timid sips of water, looking at or nipping the side just behind the elbow, a deep stretch, eating interrupted.",
    means: "Seen in 24 of 26 horses with gastric ulcers or impaction and none of 4 healthy horses (small study). A camera cannot diagnose ulcers: only 1 of 52 ulcer horses crib-bit, and most signs showed under saddle.",
    confuse: "Flies; normal stretching after lying.",
    equicare: { status: "label", how: "Not detected." },
    sources: ["torcivia2025", "pimenta2026"] },
  { id: "pica", group: "feeding", name: "Eating soil or non-food", label: null, specificity: "weak",
    looks: "Licks or eats soil, walls or other non-food.",
    means: "A mineral need or boredom; soil eaten had more iron and copper. Sand colic risk.",
    confuse: "Nibbling straw bedding (normal when forage runs out).",
    equicare: { status: "label", how: "Not detected." },
    sources: ["mcgreevy2001"] },

  // ---- stable vices ------------------------------------------------------ //
  { id: "self_biting", group: "vices", name: "Self-biting", label: null, specificity: "strong",
    looks: "Bites its own flank or chest, often with bucking or kicking out.",
    means: "Up to 2% of stallions. Three kinds: discomfort, self-directed aggression, stereotypic. Injury risk — vet. Castration improved 7 of 10 stallions.",
    confuse: "Biting at flies.",
    equicare: { status: "label", how: "Not detected." },
    sources: ["mcdonnell2008"] },

  // ---- stress, mood & company -------------------------------------------- //
  { id: "withdrawn", group: "welfare", name: "Withdrawn posture", label: null, specificity: "weak",
    looks: "Stands still with eyes open and a fixed stare, neck stretched level with the back, ears back, no head or ear movement, ignoring what goes on around — bouts of 17–97 s.",
    means: "A depression-like state in 24% of 59 riding-school horses (lower cortisol, less interest in pleasant things); may reveal chronic pain. More likely the longer a horse is boxed. A welfare concern for days, not an emergency.",
    confuse: "Dozing — eyes half closed, lower lip loose, a hind leg rested.",
    equicare: { status: "prototype", how: "From the camera: standing still in 20 s+ bouts with the head no higher than the back (or turned away), not at the hay — in the daytime, against the horse's own usual — and not reacting when people come to the stall. 'Dull or withdrawn'. The eyes and ears are not seen, so dozing can look alike: hence daytime only, its own usual, and the reactions to people." },
    sources: ["fureix2012", "ruet2019"] },
  { id: "ears_back", group: "welfare", name: "Ears back most of the time", label: null, specificity: "weak",
    looks: "Both ears turned back for most of the time at rest, or while eating hay.",
    means: "In 59 horses, those with ears back in half or more of checks had more health problems, back problems and stereotypies (one conference study). Ears back while eating hay is part of a chronic-stress score and is commoner with restricted forage.",
    confuse: "Listening behind; a neighbour nearby; flies.",
    equicare: { status: "label", how: "Not detected; ears may be visible but are small at stall distance." },
    sources: ["fureix2011_ears", "phelipon2024", "stomp2018"] },
  { id: "calm_attention", group: "welfare", name: "Calm and interested (good welfare)", label: null, specificity: "normal",
    looks: "Slow exploring walk, ears and neck moving to scan, eating, relaxed lower lip; lies down to rest.",
    means: "Marks good welfare. Standing fixed and still for more than 15% of checks, with more fixed than roaming attention, marked poor welfare in one study. More lying is consistently a positive sign.",
    confuse: "—",
    equicare: { status: "prototype", how: "Moving and resting time are measured; attention is not." },
    sources: ["hausberger2026", "hallkay2024"] },
  { id: "snorting", group: "welfare", name: "Snorting (a good sign)", label: null, specificity: "normal",
    looks: "A pulsed, fluttering breath out through the nose, mouth closed, ears forward.",
    means: "A sign of positive emotion: 7–13 snorts an hour; fewer in horses with more chronic stress (r = −0.41) and in stereotypic horses. A short, sharp unpulsed 'blow' is the alarm sound, not the snort.",
    confuse: "Clearing the nose at dusty hay; headshaking.",
    equicare: { status: "sensor", how: "Needs a microphone." },
    sources: ["stomp2018"] },
  { id: "separation_calls", group: "welfare", name: "Calling when a neighbour leaves", label: null, specificity: "weak",
    looks: "Long whinnies when a companion is taken out; short ones when it returns.",
    means: "Separation stress; the whinny's higher pitch and length rise in negative situations. Changing a horse's neighbours is a stressor in itself.",
    confuse: "Calling at feed time.",
    equicare: { status: "sensor", how: "Needs a microphone." },
    sources: ["briefer2015"] },
  { id: "neighbour_contact", group: "welfare", name: "Seeing and touching neighbours", label: null, specificity: "normal",
    looks: "Whether the horse can see and touch the horse next door.",
    means: "Horses kept without contact had higher stress hormones and higher eye temperature than horses with company, and were harder to handle. Touch through a grille reduced abnormal behaviour more than sight alone; a mirror reduced weaving. Police horses on bare floors in 2 × 2.5 m stalls showed abnormal behaviour 17% of the time in a test.",
    confuse: "—",
    equicare: { status: "label", how: "Stable layout; note it with the horse's record." },
    sources: ["yarnell2015", "phelipon2024", "mcafee2002", "schork2018"] },
  { id: "yawning", group: "welfare", name: "Repeated yawning", label: null, specificity: "weak",
    looks: "Several yawns in a row.",
    means: "Stereotypic horses yawn more, and in the same periods as their stereotypy. Yawning is also catching between horses, so one yawn means little.",
    confuse: "Waking up; after feeding.",
    equicare: { status: "label", how: "Not detected." },
    sources: ["fureix2011_yawn"] },
  { id: "eye_signs", group: "welfare", name: "Blinking, eyelid twitches, eye wrinkles", label: null, specificity: "weak",
    looks: "Full blinks, small eyelid twitches and the wrinkles above the eye.",
    means: "Under stress full blinks fell from 8–9 to about 5 a minute and eyelid twitches rose from 2 to 6; the wrinkle angle rose with food competition. Valid, but measured with a camera pointed straight at the eye.",
    confuse: "Light, dust, flies.",
    equicare: { status: "not_visible", how: "A stall camera at 3–4 m cannot count them." },
    sources: ["merkies2019", "hintze2016"] },

  // ---- rest & sleep ------------------------------------------------------ //
  { id: "collapse_standing", group: "rest", name: "Buckling or collapsing while dozing", label: null, specificity: "strong",
    looks: "At night a standing, dozing horse suddenly drops its head or front end and buckles at the knees, then catches itself.",
    means: "Sleep (REM) deprivation — the horse cannot or will not lie down. Repeated collapses injure the knees and fetlocks. Vet, and look at pain, stall size, bedding and company.",
    confuse: "Normal swaying while dozing (no drop).",
    equicare: { status: "prototype", how: "From the camera (the whole horse in view): dozing standing for a minute, the top of the horse's box drops 15%+ of its height with a jolt and comes back within 6 s — 'Knees buckling while dozing'. Down to the ground within ~1.5 s with no circling first is 'Went down suddenly'. The edge looks 4 times a second while the horse dozes. Our rule; not yet checked against filmed collapses." },
    sources: ["fuchs2017", "aleman2008", "kelemen2021"] },
  { id: "getting_up", group: "rest", name: "Difficulty getting up", label: null, specificity: "strong",
    looks: "Several attempts to rise, a long sitting phase, or rolling over before getting up more than usual.",
    means: "Normal nights hold about 4 get-ups, each at the first attempt; a half-roll before rising happens in 12–33% (more in small boxes). More effort or attempts points to musculoskeletal pain or a too-small stall; cannot rise — vet now.",
    confuse: "A single half-roll before rising.",
    equicare: { status: "prototype", how: "Get-up events from the posture model; a reviewed get-up is described in the night report. Attempts are not counted yet." },
    sources: ["raabymagle2006", "torcivia2021"] },

  // ---- normal — don't alarm --------------------------------------------- //
  { id: "night_to_night", group: "normal", name: "Night-to-night variation", label: null, specificity: "normal",
    looks: "The same healthy horse lies, eats and moves differently from one night to the next.",
    means: "Large: standing time varied by a median 47 min a day and grazing by 77 min in pasture horses; young horses' lying varied widely between nights. One unusual night is not an alarm — compare with the horse's own 7–14 nights, and look for two or more measures moving together.",
    confuse: "A real change (persists over several nights, with other signs).",
    equicare: { status: "prototype", how: "Behaviour notes compare with the horse's own 7-day level." },
    threshold: { text: "The 7–14-night baseline and 'two measures together' rule come from cattle monitoring studies; no horse study sets them.", ours: true },
    sources: ["helmerich2025", "maisonpierre2019"] },
  { id: "oestrus", group: "normal", name: "Mare in season", label: null, specificity: "normal",
    looks: "Frequent squatting urination with little volume, tail raised, 'winking', squealing at a neighbour — for 5–7 days about every 21 days.",
    means: "Normal oestrus. Each mare shows it the same way each cycle, so learn her signs to avoid false pain alerts (frequent urination posture is also a discomfort sign).",
    confuse: "Urinary problems; colic ('urination stance without a stream').",
    equicare: { status: "label", how: "Not detected; mark cycles on the horse's record." },
    sources: ["coleman2004"] },

  // ---- foaling ---------------------------------------------------------- //
  { id: "foaling_imminent", group: "foaling", name: "Birth within 1–2 hours", label: null, specificity: "strong",
    looks: "Restlessness rising from about 2 h before birth, most in the last 30–20 min; repeated lying down and getting up, rolling, tail raised, stops eating.",
    means: "Imminent foaling. Sensor alarms gave about 30–60 min warning; lower tail-skin temperature plus lying down was the most precise in the last hour. Call the attendant — but disturbing the mare lengthened delivery (5.3 vs 1.6 min), so watch from outside.",
    confuse: "Colic (no due date, no udder change).",
    equicare: { status: "label", how: "Not detected; the thermal tail-skin idea is untested." },
    sources: ["hartmann2018", "jung2022", "aoki2023", "melchert2019"] },
];

/** Things no open-access source provides — any number here is ours. */
export const GAPS = [
  "Rolls or lie-downs per hour that mean colic.",
  "How many hours before a natural colic eating, droppings, lying or activity change.",
  "The hours of the day when colic most often starts.",
  "A time limit for lying down, or for lying flat on the side.",
  "A rhythm or minimum number of cycles for weaving.",
  "How long each urination lasts, or how much is passed each time.",
  "A 'no manure for X hours' alarm threshold.",
  "An eye-temperature fever threshold (eye readings do not reliably track rectal temperature, and the offset depends on camera and distance).",
  "What a sudden drop in a stereotypy means.",
  "Anything on thermal images of fresh urine or manure.",
  "Lying and sleep of horses in heat above 30 °C.",
  "Whether drinking (swallowing) can be seen on stall video.",
  "Behaviour norms for Marwari, Kathiawari or Indian country-bred horses, or for Indian Army horses.",
  "Peer-reviewed validation of commercial colic alarms.",
];

export function knowledge() {
  return { compiled: "2026-10-04", groups: GROUPS, patterns: PATTERNS, sources: SOURCES, gaps: GAPS };
}

/** The pattern a footage label belongs to, for tooltips. */
export function patternForLabel(key) {
  return PATTERNS.find((p) => p.label === key) || null;
}
