// What horse behaviour patterns mean — from open-access veterinary sources.
//
// Every pattern cites the sources it rests on (ids in SOURCES). Where no source
// gives a number, the entry says so: thresholds EquiCare uses in those places
// are our operational choice, marked `ours: true`, and belong in front of a vet.
// `equicare` says honestly what the system can observe today:
//   measured     — read by the camera now
//   prototype    — a camera heuristic exists but is not validated on horses
//   label        — no detector yet; staff mark it on footage to teach one
//   sensor       — needs other hardware (IMU, flow meter)
//   not_visible  — a stall camera at 3–4 m cannot see it
// Compiled 2026-09-27 from ~55 open-access sources (paywalled originals are cited
// through the open papers that describe them).

export const SOURCES = {
  merck_colic:       { title: "Merck Vet Manual — Overview of Colic in Horses (Moore, 2026)", url: "https://www.merckvetmanual.com/digestive-system/colic-in-horses/overview-of-colic-in-horses", kind: "vet manual" },
  maskato2020:       { title: "Maskato et al. 2020, Animals — Equine Acute Abdominal Pain Scale (EAAPS) revalidation", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC7760242/", kind: "peer-reviewed" },
  vandierendonck2020:{ title: "van Dierendonck et al. 2020 — EQUUS-COMPASS / FAP items (donkey version)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC7070438/", kind: "peer-reviewed" },
  auer2021:          { title: "Auer et al. 2021, Animals — Activity time budgets as a welfare tool", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8002676/", kind: "peer-reviewed" },
  torcivia2021:      { title: "Torcivia & McDonnell 2021 — Equine Discomfort Ethogram", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC7931104/", kind: "peer-reviewed" },
  dallacosta2014:    { title: "Dalla Costa et al. 2014, PLOS ONE — Horse Grimace Scale", url: "https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0092281", kind: "peer-reviewed" },
  gleerup2015:       { title: "Gleerup et al. 2015 — An equine pain face", url: "https://pubmed.ncbi.nlm.nih.gov/25082060", kind: "peer-reviewed", access: "abstract" },
  ask2020:           { title: "Ask et al. 2020, Animals — Pain behaviour in the box", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC7699379/", kind: "peer-reviewed" },
  broome2019:        { title: "Broomé et al. 2019, CVPR — Pain recognition from video over time", url: "https://arxiv.org/abs/1901.02106", kind: "peer-reviewed" },
  merck_laminitis:   { title: "Merck Vet Manual — Laminitis in Horses", url: "https://www.merckvetmanual.com/musculoskeletal-system/disorders-of-the-foot-in-horses/laminitis-in-horses", kind: "vet manual" },
  rutgers_tpr:       { title: "Rutgers NJAES FS1262 — Temperature, pulse and respiration", url: "https://njaes.rutgers.edu/fs1262/", kind: "extension" },
  merck_resp:        { title: "Merck Vet Manual — Respiratory Diseases of Horses", url: "https://www.merckvetmanual.com/respiratory-system/respiratory-diseases-of-horses/overview-of-respiratory-diseases-of-horses", kind: "vet manual" },
  lampang2023:       { title: "Na Lampang et al. 2023, Vet World — Infrared vs rectal temperature in horses", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10844792", kind: "peer-reviewed" },
  transport_eye2024: { title: "2024 — Eye temperature, rectal temperature and cortisol after transport", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11240744/", kind: "peer-reviewed" },
  alberghina2025:    { title: "Alberghina et al. 2025, Frontiers — Non-contact thermometry reference intervals", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12043634/", kind: "peer-reviewed" },
  merck_parturition: { title: "Merck Vet Manual — Parturition in Horses", url: "https://www.merckvetmanual.com/management-and-nutrition/management-of-reproduction-horses/parturition-in-horses", kind: "vet manual" },
  csu_foaling:       { title: "Colorado State Univ. ERL — Prediction of foaling and normal foaling", url: "https://vetmedbiosci.colostate.edu/erl/2022/12/01/prediction-of-foaling-and-normal-foaling/", kind: "extension" },
  merck_perinatal:   { title: "Merck Vet Manual — Perinatal Mare and Foal Care", url: "https://www.merckvetmanual.com/management-and-nutrition/preventative-health-care-and-husbandry-of-horses/perinatal-mare-and-foal-care", kind: "vet manual" },
  hausberger2009:    { title: "Hausberger et al. 2009, PLoS ONE — Abnormal repetitive behaviours in working horses", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC2763287/", kind: "peer-reviewed" },
  merck_behaviour:   { title: "Merck Vet Manual — Behavior Problems of Horses (Houpt, 2025)", url: "https://www.merckvetmanual.com/behavior/behavior-of-horses/behavior-problems-of-horses", kind: "vet manual" },
  ufifas_vm257:      { title: "UF/IFAS VM257 — Stereotypic behaviours in horses", url: "https://ask.ifas.ufl.edu/publication/VM257", kind: "extension" },
  brauns2025:        { title: "Brauns et al. 2025, Animals — Repetitive behaviour episode rule", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12523708/", kind: "peer-reviewed" },
  mata2024:          { title: "Mata, Boyton & Young 2024, Animals — Behaviour before feeding", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11672559/", kind: "peer-reviewed" },
  mazzola2016:       { title: "Mazzola et al. 2016, Vet Med Int — Stereotypies and feeding", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5081461/", kind: "peer-reviewed" },
  mejia2022:         { title: "Mejía et al. 2022, Vet World — Stereotypies in Colombian Creole horses", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC9178590/", kind: "peer-reviewed" },
  cortisol2024:      { title: "PLoS ONE 2024 — Competition and stereotypic behaviour in Thoroughbreds (cortisol)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11458048/", kind: "peer-reviewed" },
  nowak2024:         { title: "Nowak et al. 2024, Front Pain Res — Weight shifting and pain", url: "https://www.frontiersin.org/journals/pain-research/articles/10.3389/fpain.2024.1410302/full", kind: "peer-reviewed" },
  rutgers_manure:    { title: "Westendorf & Krogmann 2006, Rutgers — Horse manure management", url: "https://esc.rutgers.edu/fact_sheet/horse-manure-management-bedding-use/", kind: "extension" },
  lpelc:             { title: "LPELC — Stall waste production and management", url: "https://lpelc.org/stall-waste-production-and-management/", kind: "extension" },
  outouil2026:       { title: "Outouil et al. 2026, JAALAS — Stall size and behaviour", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC13446403/", kind: "peer-reviewed" },
  williams2015:      { title: "Williams et al. 2015, Equine Vet J — Pasture to stable: faecal output and gut motility", url: "https://pubmed.ncbi.nlm.nih.gov/24528106/", kind: "peer-reviewed" },
  merck_urolith:     { title: "Merck Vet Manual — Urolithiasis in Horses (Divers, 2025)", url: "https://www.merckvetmanual.com/urinary-system/noninfectious-diseases-of-the-urinary-system-in-large-animals/urolithiasis-in-horses", kind: "vet manual" },
  griffin2019:       { title: "Griffin 2019, Univ. Kentucky / eXtension — Horse feeding behaviour", url: "https://horses.extension.org/horse-feeding-behavior/", kind: "extension" },
  giannone2026:      { title: "Giannone et al. 2026, Vet Quarterly — Deep-learning stall video study", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC13126938/", kind: "peer-reviewed" },
  ogilvie1994:       { title: "Ogilvie-Graham 1994 — Time budget studies in stalled horses (Edinburgh thesis)", url: "https://era.ed.ac.uk/handle/1842/29924", kind: "thesis", access: "abstract" },
  kjellberg2021:     { title: "Kjellberg et al. 2021, Animals — Lying behaviour in open barns", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8614411/", kind: "peer-reviewed" },
  kelemen2021:       { title: "Kelemen et al. 2021, Animals — Lying time, bouts and REM deprivation", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8614510/", kind: "peer-reviewed" },
  gobbo2025:         { title: "Gobbo et al. 2025 — Lying in riding-school horses", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12104677", kind: "peer-reviewed" },
  murase2018:        { title: "Murase et al. 2018, J Equine Sci — Foal lying behaviour", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC6145866/", kind: "peer-reviewed" },
  zimmer2026:        { title: "Zimmer et al. 2026, Frontiers Vet Sci — Sleep architecture and lying behaviour (EEG)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC13491436/", kind: "peer-reviewed" },
  burla2017:         { title: "Burla et al. 2017, Frontiers Vet Sci — Bedding and lying", url: "https://www.frontiersin.org/journals/veterinary-science/articles/10.3389/fvets.2017.00023/full", kind: "peer-reviewed" },
  merck_emergency:   { title: "Merck Vet Manual — Emergency care for horses", url: "https://www.merckvetmanual.com/special-pet-topics/emergencies/emergency-care-for-horses", kind: "vet manual" },
  ext_tpr:           { title: "eXtension — Temperature, pulse and respiration in a horse", url: "https://horses.extension.org/temperature-pulse-and-respiration-in-a-horse/", kind: "extension" },
  psu_colic:         { title: "Penn State Extension — Colic: signs and management", url: "https://extension.psu.edu/colic-what-are-the-signs-and-how-to-manage", kind: "extension" },
  psu_healthy:       { title: "Penn State Extension — Recognizing a healthy horse", url: "https://extension.psu.edu/recognizing-a-healthy-horse", kind: "extension" },
  merck_temp_table:  { title: "Merck Vet Manual — Normal rectal temperature ranges", url: "https://www.merckvetmanual.com/multimedia/table/normal-rectal-temperature-ranges", kind: "vet manual" },
  merck_resp_table:  { title: "Merck Vet Manual — Resting respiratory rates", url: "https://www.merckvetmanual.com/multimedia/table/resting-respiratory-rates", kind: "vet manual" },
  adriaens2022:      { title: "Adriaens et al. 2022, Wageningen — Lying down / getting up from video box features (dairy cows)", url: "https://edepot.wur.nl/584493", kind: "peer-reviewed" },
  deeposit2025:      { title: "DeePosit 2025 — Thermal detection of urine and faeces deposits (mice)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12393880/", kind: "peer-reviewed" },
  yang2025:          { title: "Yang et al. 2025, Ecol Evol — Stereotypy detection by tracking + periodicity (slow lorises)", url: "https://doi.org/10.1002/ece3.72304", kind: "peer-reviewed", access: "abstract" },
  merck_heaves:      { title: "Merck Vet Manual — Recurrent airway obstruction (heaves)", url: "https://www.merckvetmanual.com/horse-owners/lung-and-airway-disorders-of-horses/recurrent-airway-obstruction-heaves-in-horses", kind: "vet manual" },
};

export const GROUPS = [
  { key: "colic_pain", name: "Colic & pain" },
  { key: "vices",      name: "Stable vices (stereotypies)" },
  { key: "rest",       name: "Rest & sleep" },
  { key: "elimination", name: "Urination & manure" },
  { key: "vitals",     name: "Temperature & breathing" },
  { key: "foaling",    name: "Foaling & foals" },
  { key: "normal",     name: "Normal — don't alarm" },
];

// specificity: strong  — a reliable sign on its own
//              weak    — means little alone; look for clusters
//              normal  — normal behaviour, context for other signs
export const PATTERNS = [
  // ---- colic & pain ------------------------------------------------------ //
  { id: "rolling", group: "colic_pain", name: "Rolling", label: "rolling", specificity: "strong",
    looks: "Goes down and rolls onto the back or side, often repeatedly. Normal dust-bathing is a single roll that ends with the horse getting up and shaking.",
    means: "Highest score (5) on the Equine Acute Abdominal Pain Scale. Rolling from standing that is not dust-bathing needs a person to look now.",
    confuse: "Dust-bathing after work or a bedding change; foals and new bedding bring more rolling.",
    equicare: { status: "prototype", how: "'Possible roll': the horse is down, a burst of movement, and its box height swings (our rule; no published video roll detector exists). Our motion test on open clips: rolling median 0.41 vs eating 0.05. Label rolls on footage to validate." },
    sources: ["maskato2020", "merck_colic", "auer2021"] },
  { id: "down_up", group: "colic_pain", name: "Repeatedly lying down and getting up", label: "lies_down", specificity: "strong",
    looks: "Lies down, gets up within minutes, lies down again. The ethogram calls it 'frequent interrupted recumbent rests'.",
    means: "Abdominal pain (colic). Normal lying bouts last about 15–40 min.",
    confuse: "A horse settling on new bedding; first nights in a new stall.",
    equicare: { status: "prototype", how: "Lie-down and get-up events from the horse's box shape over time on the colour picture (method validated on dairy cows: 92 % of get-ups, 80–87 % of lie-downs), learned per stall. Needs the optional detector. Watch note at 3+ lie-downs within an hour." },
    threshold: { text: "No published count per hour exists. Our watch note: 3+ lie-downs within an hour.", ours: true },
    sources: ["merck_colic", "torcivia2021", "maskato2020", "psu_colic", "adriaens2022"] },
  { id: "flank_watching", group: "colic_pain", name: "Flank watching", label: "flank_watching", specificity: "strong",
    looks: "Turns the head back towards the flank or belly and holds it, or does so again and again.",
    means: "Score 1 on EAAPS; repeated flank watching is a strong colic sign.",
    confuse: "Scratching or biting at flies — brief, with the mouth on the coat.",
    equicare: { status: "label", how: "No detector. Label it to teach one." },
    sources: ["maskato2020", "merck_colic"] },
  { id: "kick_belly", group: "colic_pain", name: "Kicking at the belly", label: "kick_at_belly", specificity: "strong",
    looks: "Lifts a hind leg and kicks forward, towards the belly.",
    means: "Score 3 on EAAPS; a strong colic sign.",
    confuse: "Stamping at flies on the legs (foot goes down, not forward under the belly).",
    equicare: { status: "label", how: "No detector. Label it to teach one." },
    sources: ["maskato2020", "merck_colic"] },
  { id: "pawing", group: "colic_pain", name: "Pawing", label: "pawing", specificity: "weak",
    looks: "Scrapes the floor repeatedly with a front hoof.",
    means: "Score 3 on EAAPS when part of a pain picture — but on its own it is common frustration or feed anticipation.",
    confuse: "Waiting for feed (rises in the 20 min before a meal); Merck also lists pawing as a locomotor stereotypy.",
    equicare: { status: "label", how: "No detector. Label it; read it together with the time of the next feed." },
    sources: ["maskato2020", "merck_colic", "mata2024", "merck_behaviour"] },
  { id: "stretch_urinate", group: "colic_pain", name: "Stretching as if to urinate", label: "stretch_as_if_to_urinate", specificity: "strong",
    looks: "Takes the urination stance — hind legs back, body stretched — with effort but no stream, or only a little.",
    means: "Abdominal pain (colic); the ethogram lists the urination stance without a stream as a sign. Frequent small urinations point to bladder stones or cystitis instead.",
    confuse: "Normal urination (a full stream follows).",
    equicare: { status: "label", how: "The floor-patch detector sees urine, not the stance. Label the stance to teach it." },
    sources: ["merck_colic", "torcivia2021", "merck_urolith"] },
  { id: "lateral_awake", group: "colic_pain", name: "Lying flat on the side while awake", label: "lying_lateral", specificity: "strong",
    looks: "Lies flat on the side with the head down but is awake — head lifting, legs moving, or repositioning again and again.",
    means: "Score 4 on EAAPS. Lateral lying is also normal deep (REM) sleep — the difference is that a sleeping horse is still.",
    confuse: "Normal REM sleep: about 20 min a day flat out, still, mostly 00:00–05:00.",
    equicare: { status: "prototype", how: "'Possibly flat on the side': lying with a longer, lower box than this horse usually lies with — or the detector losing a lying horse, which it does for horses flat out (open-photo test: found 13/14 chest-lying, 0/4 flat). Cannot tell awake from asleep." },
    threshold: { text: "No published time limit. Normal single lying bouts stayed at or under ~57 min; our watch note is 60 min flat in 90 min.", ours: true },
    sources: ["maskato2020", "torcivia2021", "kelemen2021", "zimmer2026"] },
  { id: "restless", group: "colic_pain", name: "Restlessness", label: null, specificity: "weak",
    looks: "Moves about the box more than usual, cannot settle.",
    means: "Score 2 on EAAPS; with other signs it points to pain, alone it may be anticipation or excitement.",
    confuse: "The 20 minutes before a meal; a neighbour leaving; first days in a new stall.",
    equicare: { status: "prototype", how: "Camera activity (colour picture by default), compared with this horse's own 7-day level ('Activity unusual for this horse'). A watch note, never an alarm." },
    sources: ["maskato2020", "mata2024", "auer2021"] },
  { id: "dull_back_of_box", group: "colic_pain", name: "Dull, head low, at the back of the box", label: null, specificity: "weak",
    looks: "Stands away from the door with the head low, not interested in people or surroundings, may lean on the wall.",
    means: "Pain in the box (Ask 2020: position in the box, head position, interest). After severe colic, a quiet horse can mean it is getting worse (endotoxaemia), not better.",
    confuse: "Dozing — relaxed, a hind leg rested, and it wakes easily.",
    equicare: { status: "prototype", how: "Only as low activity versus the horse's own level; position in the box is not measured yet." },
    sources: ["ask2020", "torcivia2021", "merck_colic"] },
  { id: "weight_shifting", group: "colic_pain", name: "Frequent weight shifting", label: null, specificity: "weak",
    looks: "Shifts weight from leg to leg again and again while standing.",
    means: "Pain: a median of 2 shifts per hour without pain vs 13 per hour in severe pain.",
    confuse: "Weaving (rhythmic side-to-side with the head and neck); resting a hind leg (normal).",
    equicare: { status: "label", how: "Not detectable at 176×144 px; needs a limb-level model." },
    sources: ["nowak2024"] },
  { id: "rocking_back", group: "colic_pain", name: "Rocking-back stance", label: null, specificity: "strong",
    looks: "Weight on the hind legs with both front feet placed out in front of the body; reluctant to move or get up.",
    means: "Front-foot laminitis. Needs a vet: pulses and hoof heat are hands-on checks.",
    confuse: "Parked-out stance to urinate (brief).",
    equicare: { status: "label", how: "Use 'Other' with a note; lameness is measured later by other sensors." },
    sources: ["merck_laminitis", "torcivia2021"] },
  { id: "pain_face", group: "colic_pain", name: "Pain face (grimace)", label: null, specificity: "weak",
    looks: "Ears stiff and back, tightened eyes, tension above the eye, tense chewing muscles, strained mouth and nostrils.",
    means: "Pain (Horse Grimace Scale 0–12). Observers agree less on face than on body signs, and nostrils agree least.",
    confuse: "Drowsiness, flies, bright light.",
    equicare: { status: "not_visible", how: "Needs a close, front-on, well-lit face. A stall camera 3–4 m away cannot score it." },
    sources: ["dallacosta2014", "gleerup2015", "vandierendonck2020", "ask2020", "broome2019"] },

  // ---- stable vices ------------------------------------------------------ //
  { id: "weaving", group: "vices", name: "Weaving", label: "weaving", specificity: "strong",
    looks: "Obvious side-to-side swaying of the head, neck and forequarters, sometimes the hindquarters, in the same spot — often at the stall front.",
    means: "A stereotypy linked to confinement, isolation and grain-heavy diets. It peaks around feeding. It may help the horse cope (stereotypic horses had lower cortisol), so a sudden stop is not automatically good news.",
    confuse: "Weight shifting from pain (not rhythmic); restlessness at the door before meals.",
    equicare: { status: "prototype", how: "A regular, persistent, mostly sideways rhythm of the moving mass, 0.25–2 Hz, on the colour picture — the tracking + periodicity method a zoo study used for stereotypic pacing (96.7 % precision). Reported as minutes per day and episodes, against the horse's own level. Not yet seen on a real weaver." },
    threshold: { text: "No source gives a weaving frequency or minimum cycle count. We search 0.25–2 Hz and join bouts under 10 min apart (Sambraus 1989: 67 min/day on average in 27 weavers).", ours: true },
    sources: ["hausberger2009", "merck_behaviour", "ufifas_vm257", "brauns2025", "cortisol2024", "yang2025"] },
  { id: "crib_biting", group: "vices", name: "Crib-biting / wind-sucking", label: "crib_biting", specificity: "strong",
    looks: "Grips a fixed edge (door, manger) with the front teeth, arches the neck, pulls back and gulps air, often with a grunt. Wind-sucking is the same without gripping anything.",
    means: "A stereotypy linked to gastric ulcers in young horses and to one type of colic (epiploic foramen entrapment). Peaks after concentrate feed. Once established it persists.",
    confuse: "Normal chewing of wood or the feeder — no arch, no grunt.",
    equicare: { status: "label", how: "No detector (would need a model or a microphone). Label it to teach one." },
    sources: ["hausberger2009", "merck_behaviour", "ufifas_vm257", "mazzola2016"] },
  { id: "box_walking", group: "vices", name: "Box walking", label: "box_walking", specificity: "strong",
    looks: "Walks the stall perimeter again and again. Two kinds: slow, silent circling, or fast walking with neighing.",
    means: "The fast, calling kind means confinement distress; if it happens only when a neighbour leaves, separation anxiety.",
    confuse: "A new horse exploring; anticipation before feed.",
    equicare: { status: "prototype", how: "Laps of the stall: a slow (7–30 s), wide back-and-forth of where the movement is while the horse stays busy. No published kinematics — our rule." },
    sources: ["merck_behaviour", "ufifas_vm257"] },
  { id: "head_tossing", group: "vices", name: "Head nodding / tossing", label: "head_tossing", specificity: "weak",
    looks: "Repetitive up-and-down bobbing of the head, or sudden bouts of tossing.",
    means: "May be a stereotypy — but head shaking has many medical causes (ear, eye, respiratory disease, pain). A camera cannot tell which: a vet should see a new head-shaker.",
    confuse: "Tossing at flies.",
    equicare: { status: "prototype", how: "A regular up-down rhythm while the horse stays in place (a walking horse nods with each stride). Irregular tossing is not counted — that points to discomfort or flies." },
    sources: ["hausberger2009", "merck_behaviour"] },
  { id: "vice_timing", group: "vices", name: "When vices happen", label: null, specificity: "normal",
    looks: "In ration-fed horses stereotypies rose from 2.2 to 7.2 per hour before a feed, mostly in the last 20 min; cribbing peaks after concentrate.",
    means: "Watch the hour before and after each meal. More vice time suggests more stress or a feeding change.",
    confuse: "Prevalence estimates differ by population: 4–5% oral stereotypies, over 15% overall, 32% in one breed study.",
    equicare: { status: "prototype", how: "Weaving events are time-stamped; feed times are not linked yet." },
    sources: ["mata2024", "mazzola2016", "ufifas_vm257", "mejia2022"] },

  { id: "eating_time", group: "normal", name: "Eating time", label: "eating", specificity: "normal",
    looks: "Head at hay, manger or floor, chewing.",
    means: "Stabled horses on set rations eat for as little as 3–4 h a day (8–14 h when grazing; 8.7 h measured in 80 stalled horses on more forage). Pain lowers eating time — a drop against the horse's own level matters more than the number.",
    confuse: "Mouthing bedding or chewing wood.",
    equicare: { status: "sensor", how: "Feed intake comes from the feeder sensor later; label eating to teach the camera." },
    sources: ["merck_behaviour", "griffin2019", "ogilvie1994", "auer2021"] },
  { id: "drinking_time", group: "normal", name: "Drinking", label: "drinking", specificity: "normal",
    looks: "Muzzle in the water, swallowing.",
    means: "A camera study of stalled horses found drinking peaked 16:00–22:00. Water intake rose sharply after moving from pasture to a stable. No primary source gives a normal number of drinking bouts.",
    confuse: "Playing with the water.",
    equicare: { status: "sensor", how: "Measured by the flow meter once fitted." },
    sources: ["giannone2026", "williams2015"] },

  // ---- rest & sleep ------------------------------------------------------ //
  { id: "normal_lying", group: "rest", name: "Lying down (normal)", label: "lying", specificity: "normal",
    looks: "Lies on the chest (sternal), legs folded; or flat on the side for deep sleep.",
    means: "Normal rest. Adults lie about 5% of the day — measured means range from 25 to 67 min a day (0–319 min between horses) — mostly 00:00–05:00, in 2–4 bouts of ~10–16 min (up to 57).",
    confuse: "—",
    equicare: { status: "prototype", how: "Lying minutes, bouts and the longest bout from the horse's box on the colour picture, once the stall's standing and lying shapes are learned (optional detector). Stillness alone is not lying." },
    sources: ["auer2021", "kelemen2021", "gobbo2025", "ogilvie1994", "zimmer2026", "adriaens2022"] },
  { id: "rem_deprivation", group: "rest", name: "Too little lying (REM deprivation)", label: null, specificity: "strong",
    looks: "Falls asleep standing and buckles at the knees; scrapes on the front of the knees and front fetlocks.",
    means: "Horses need at least 30 min of lying a day for REM sleep. Horses with these signs lay down only ~8 min a day. Causes: too little space, poor bedding, pain, social stress.",
    confuse: "A new stall (lying is suppressed for the first 1–4 nights).",
    equicare: { status: "prototype", how: "Watch note after 3 nights the camera saw (6 h+ each) with under 10 min lying." },
    sources: ["kelemen2021", "zimmer2026", "burla2017"] },
  { id: "standing_rest", group: "rest", name: "Dozing standing up", label: "standing_still", specificity: "normal",
    looks: "Stands still, head lowered, eyes half closed, one hind leg resting on the toe.",
    means: "Normal: adults take about 80% of their rest standing. Resting a hind leg is normal; pointing a front leg for long is not.",
    confuse: "A dull, painful horse (head low but tense, no hind leg rested, not interested when approached).",
    equicare: { status: "prototype", how: "Counted as 'still' minutes — stillness, not lying." },
    sources: ["auer2021", "torcivia2021"] },

  // ---- urination & manure ----------------------------------------------- //
  { id: "manure_frequency", group: "elimination", name: "Manure frequency", label: "defecating", specificity: "normal",
    looks: "Tail lifted, droppings passed — 4 to 13 times a day for a 1,000 lb horse.",
    means: "Fewer droppings is a colic sign, as is straining. Moving from pasture to a stable more than halved faecal output in one study, mostly in the first 5 days — a known colic-risk window.",
    confuse: "—",
    equicare: { status: "prototype", how: "In the colour picture, where a floor box is drawn over bedding: a new compact, dark, textured pile on the bedding after the horse moves away — our method, untested on horses. Where the floor is also in the thermal view: a new warm patch classified by how it cools (the method a mouse study used: F1 0.90 for faeces); both together count as confirmed. Notes: 12 h without manure, or under half the horse's usual daily count." },
    threshold: { text: "No source gives a 'no manure for X hours' alarm. Ours: 12 h, or under 50 % of the horse's own daily count — and always check when it last ate (fasting cuts output 55–63 %).", ours: true },
    sources: ["rutgers_manure", "lpelc", "merck_colic", "williams2015", "outouil2026", "deeposit2025"] },
  { id: "urination", group: "elimination", name: "Urination", label: "urinating", specificity: "normal",
    looks: "Stretched stance, stream of urine; about 9 L a day in total.",
    means: "Frequent small urinations, straining, dribbling or blood point to bladder stones or cystitis (vet). The stance without a stream is a colic sign.",
    confuse: "—",
    equicare: { status: "prototype", how: "In the colour picture: bedding going darker where it is wet, a wider smooth patch (shows well on shavings, poorly on straw). In the thermal view, if the floor is in it: a warm patch that cools within minutes (split set by the floor cooling test). 'No urination seen' note only when urination has been seen here in the last 3 days. The stance itself is not detected." },
    threshold: { text: "No open-access source gives a normal number of urinations a day (the '7–10' figure is not from a primary source). Our 8 h note is our choice.", ours: true },
    sources: ["rutgers_manure", "lpelc", "merck_urolith", "merck_colic", "deeposit2025"] },

  // ---- vitals ------------------------------------------------------------ //
  { id: "eye_temperature", group: "vitals", name: "Eye temperature (thermal camera)", label: null, specificity: "weak",
    looks: "The hottest point in the eye corner, read by the thermal camera.",
    means: "Averages ~35 °C, about 2 °C below rectal; one study found no significant correlation with rectal temperature, another found it tracked rectal temperature and stress after transport. Use it as each horse's own trend, and confirm a fever with a rectal thermometer.",
    confuse: "Water sprays, sweat, humidity and a cold stall all change the eye reading.",
    equicare: { status: "measured", how: "The eye box's hottest pixel — or, when the head is elsewhere in the thermal view, the hottest eye-like point on it (33–41 °C, with warm head around it). Alerts compare with this horse's own 7-day baseline: +1.0 °C watch, +1.5 °C alert. Before 3 days of baseline only a reading at the rectal fever line (38.6 °C) alerts." },
    threshold: { text: "The +1.0 / +1.5 °C steps are our choice; no published eye-temperature threshold exists.", ours: true },
    sources: ["lampang2023", "transport_eye2024", "alberghina2025"] },
  { id: "rectal_temperature", group: "vitals", name: "Rectal temperature (reference)", label: null, specificity: "normal",
    looks: "Contact thermometer.",
    means: "Adults 37.2–38.6 °C (Merck: mares 37.3–38.2, stallions 37.2–38.1). Newborn foals 37.7–38.8 °C. Above 40.5 °C is overheating.",
    confuse: "Heat, exercise and excitement raise it for a while.",
    equicare: { status: "sensor", how: "Enter contact readings; they are judged against this band." },
    sources: ["merck_temp_table", "ext_tpr", "psu_healthy", "merck_emergency"] },
  { id: "resp_rate", group: "vitals", name: "Breathing rate at rest", label: null, specificity: "weak",
    looks: "Breaths per minute, from the nostril warming and cooling or the flank rising and falling.",
    means: "Adults: 10–14 (Merck), 8–12 or 10–24 (extension sources disagree). Foals: 60–80 newborn, 20–40 older. A raised rate comes with pain, fever, heat or distension — a reason to look, not a diagnosis.",
    confuse: "Heat, exercise, excitement.",
    equicare: { status: "measured", how: "Nostril box on the thermal video, referenced to the skin around it, only over 30 s+ with the head still, and only when the rate agrees with a count of breaths; fast breathing (panting) is reported as fast, not folded to a normal-looking rate. Optional flank box on the colour picture as a second opinion. Not yet verified on a live horse. Watch at 20 bpm, alert at 24." },
    sources: ["merck_resp_table", "ext_tpr", "psu_healthy", "rutgers_tpr", "merck_resp"] },
  { id: "laboured_breathing", group: "vitals", name: "Laboured breathing", label: null, specificity: "strong",
    looks: "Flared nostrils, fast breathing, a pushed breath out using the belly muscles; over time a 'heave line' along the flank.",
    means: "Airway disease such as heaves (recurrent airway obstruction) — vet.",
    confuse: "Blowing after exercise.",
    equicare: { status: "prototype", how: "Breathing regularity from the nostril signal; effort is not measured." },
    sources: ["merck_heaves", "merck_resp"] },

  // ---- foaling & foals --------------------------------------------------- //
  { id: "foaling_stage1", group: "foaling", name: "Foaling, stage 1", label: null, specificity: "weak",
    looks: "1–4 h of restlessness, sweating on the flanks and behind the elbows, lying down and getting up, rolling, frequent small droppings or urine. Most mares foal at night.",
    means: "Early labour — it looks exactly like colic, so a mare near her due date needs the due date on screen. Waxing is unreliable for timing (70–95% of mares, 6–48 h before).",
    confuse: "Colic.",
    equicare: { status: "label", how: "Label on footage; the breeding module holds due dates." },
    sources: ["merck_parturition", "csu_foaling", "merck_perinatal"] },
  { id: "foaling_stage2", group: "foaling", name: "Foaling, stage 2 (delivery)", label: null, specificity: "strong",
    looks: "Waters break; the mare lies down and strains; the foal is delivered.",
    means: "Normally 10–20 min (average 17). Call the vet if the foal is not out 15–20 min after the waters break (Merck: 30 min).",
    confuse: "—",
    equicare: { status: "label", how: "No detector." },
    sources: ["csu_foaling", "merck_parturition"] },
  { id: "foaling_stage3", group: "foaling", name: "Placenta (stage 3)", label: null, specificity: "strong",
    looks: "The placenta is passed, usually 45–90 min after the foal.",
    means: "Retained if longer than 3 h — vet.",
    confuse: "—",
    equicare: { status: "label", how: "No detector." },
    sources: ["csu_foaling", "merck_perinatal"] },
  { id: "foal_milestones", group: "foaling", name: "Newborn foal milestones", label: "nursing", specificity: "strong",
    looks: "Lies on its chest, stands, finds the udder and suckles.",
    means: "On its chest within 1 h, standing within 2 h, nursing within 3 h — missing one needs the vet. Suckling 5–7 times an hour in week 1, about once an hour by one month (extension sources only).",
    confuse: "Nuzzling the udder without swallowing.",
    equicare: { status: "label", how: "Label 'Nursing'; no detector yet." },
    sources: ["merck_perinatal"] },
  { id: "foal_lying", group: "foaling", name: "Foals lying a lot", label: null, specificity: "normal",
    looks: "Foals lie flat out often and for long.",
    means: "Normal: stalled foals lie 52–56% of the day, in 15–27 bouts, 39–48% of it flat on the side.",
    confuse: "A sick foal (does not get up to nurse).",
    equicare: { status: "sensor", how: "Adult lying rules must not be applied to foals." },
    sources: ["murase2018", "kelemen2021"] },

  // ---- normal — don't alarm --------------------------------------------- //
  { id: "pre_feed", group: "normal", name: "Busy before feeding", label: null, specificity: "normal",
    looks: "Walking, pawing, head shaking, calling and tail swishing in the last 20 min before a set feed.",
    means: "Normal anticipation, strongest in ration-fed horses.",
    confuse: "Restlessness from colic (continues after feeding, and the horse does not eat).",
    equicare: { status: "prototype", how: "Shows as higher activity; feed times are not linked yet." },
    sources: ["mata2024"] },
  { id: "day_night", group: "normal", name: "Day busy, night quiet", label: null, specificity: "normal",
    looks: "More activity 06:30–18:30; lying and sleep cluster 00:00–06:00; most eating by day.",
    means: "Normal daily rhythm.",
    confuse: "—",
    equicare: { status: "prototype", how: "Activity baselines cover whole days, so the rhythm is included." },
    sources: ["auer2021", "zimmer2026", "kjellberg2021"] },
  { id: "new_place", group: "normal", name: "New stall, first nights", label: null, specificity: "normal",
    looks: "Lies down little and sleeps poorly.",
    means: "Normal: lying and REM sleep are suppressed on night 1 and recover over nights 1–4.",
    confuse: "REM deprivation (lasts longer, with buckling).",
    equicare: { status: "prototype", how: "Baselines need 3 days before judging 'unusual' activity." },
    sources: ["zimmer2026"] },
  { id: "age_company", group: "normal", name: "Age, company and bedding", label: null, specificity: "normal",
    looks: "Older horses (18+) lie down less often and more briefly; horses in groups lie together at night; more bedded space means more lying.",
    means: "Each horse's own baseline matters more than a population number.",
    confuse: "—",
    equicare: { status: "prototype", how: "All behaviour notes compare the horse with itself." },
    sources: ["zimmer2026", "gobbo2025", "kjellberg2021", "burla2017"] },
];

/** Things no open-access source provides — any number here is ours. */
export const GAPS = [
  "Rolls or lie-downs per hour that mean colic.",
  "A time limit for lying down, or for lying flat on the side.",
  "A rhythm or minimum number of cycles for weaving.",
  "How many times a day a horse normally urinates, or how long each act lasts.",
  "A 'no manure for X hours' alarm threshold.",
  "An eye-temperature fever threshold (eye IR does not reliably track rectal temperature).",
  "What a sudden drop in a stereotypy means.",
  "Anything on thermal images of fresh urine or manure.",
];

export function knowledge() {
  return { compiled: "2026-09-27", groups: GROUPS, patterns: PATTERNS, sources: SOURCES, gaps: GAPS };
}

/** The pattern a footage label belongs to, for tooltips. */
export function patternForLabel(key) {
  return PATTERNS.find((p) => p.label === key) || null;
}
